(() => {
  const state = {
    view: 'chat', connected: false, busy: false, title: '新会话', threadId: null,
    messages: [], history: [], changes: [], attachments: [], models: [], mcpServers: [], skills: [],
    model: '', effort: 'high', approval: 'on-request', sandbox: 'workspace-write', serviceTier: 'standard',
    streamResponses: true, showReasoning: true, globalInstructions: '', projectInstructions: '',
    agents: [], activeAgentId: '', prompts: [], activePromptId: '', statusOpen: null, openMenu: null,
    composerMenu: false, composerSubmenu: null,
    settingsTab: 'basic', historySearch: '', toast: '', question: null, questionIndex: 0,
    questionAnswers: {}, agentEditor: null, promptEditor: null, skillSearch: ''
  };
  const root = document.getElementById('app');

  const icons = {
    plus: '<path d="M12 5v14M5 12h14"/>',
    history: '<path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/>',
    settings: '<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-1.6v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/>',
    search: '<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',
    edit: '<path d="m4 16-1 5 5-1L19 9l-4-4L4 16Z"/><path d="m13.5 6.5 4 4"/>',
    back: '<path d="m15 18-6-6 6-6"/>',
    paperclip: '<path d="m21 12-8.5 8.5a6 6 0 0 1-8.5-8.5l9-9a4 4 0 0 1 5.7 5.7l-9 9a2 2 0 0 1-2.9-2.8l8.4-8.4"/>',
    image: '<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="2"/><path d="m21 15-5-5L5 20"/>',
    send: '<path d="m5 12 14-7-4 14-3-6-7-1Z"/><path d="m12 13 7-8"/>',
    stop: '<rect x="7" y="7" width="10" height="10" rx="1"/>',
    branch: '<circle cx="6" cy="5" r="2"/><circle cx="18" cy="6" r="2"/><circle cx="6" cy="19" r="2"/><path d="M6 7v10M8 6h4a6 6 0 0 1 6 6v4"/>',
    code: '<path d="m8 9-3 3 3 3M16 9l3 3-3 3M14 5l-4 14"/>',
    copy: '<rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/>',
    spark: '<path d="m12 3 1.3 4.7L18 9l-4.7 1.3L12 15l-1.3-4.7L6 9l4.7-1.3L12 3Z"/>',
    sliders: '<path d="M4 7h10M18 7h2M4 17h2M10 17h10"/><circle cx="16" cy="7" r="2"/><circle cx="8" cy="17" r="2"/>',
    bolt: '<path d="m13 2-8 12h7l-1 8 8-12h-7l1-8Z"/>',
    bulb: '<path d="M9 18h6M10 22h4M8.2 14.7A7 7 0 1 1 15.8 14.7c-.8.7-1.3 1.5-1.3 2.3h-5c0-.8-.5-1.6-1.3-2.3Z"/>',
    robot: '<rect x="5" y="7" width="14" height="11" rx="3"/><path d="M12 3v4M8 12h.01M16 12h.01M9 15h6"/>',
    server: '<rect x="4" y="4" width="16" height="6" rx="2"/><rect x="4" y="14" width="16" height="6" rx="2"/><path d="M8 7h.01M8 17h.01"/>',
    note: '<path d="M6 3h12v18H6zM9 8h6M9 12h6M9 16h4"/>',
    chevron: '<path d="m9 18 6-6-6-6"/>',
    down: '<path d="m7 10 5 5 5-5"/>',
    check: '<path d="m5 12 4 4L19 6"/>',
    trash: '<path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14M10 11v6M14 11v6"/>',
    codex: '<path d="M12 3.2a4.4 4.4 0 0 1 4.2 3.1 4.4 4.4 0 0 1 1.3 8.5 4.4 4.4 0 0 1-7.4 4.6 4.4 4.4 0 0 1-6.3-6.1 4.4 4.4 0 0 1 3.2-7.4A4.4 4.4 0 0 1 12 3.2Z"/><path d="m8.2 8.1 7.6 4.4v4.2M15.8 15.9l-7.6-4.4V7.3M12 18.1V9.3"/>',
    chat: '<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4Z"/>'
  };
  const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name] || icons.code}</svg>`;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const attr = value => esc(value).replace(/`/g, '&#96;');
  const post = (action, data = {}) => window.codexHost(JSON.stringify({action, ...data}));
  const labels = {
    approval: {'untrusted':'谨慎审批','on-request':'按需审批','never':'全自动'},
    effort: {'minimal':'最少','low':'低','medium':'中','high':'高','xhigh':'极高','ultra':'最高'},
    sandbox: {'read-only':'只读','workspace-write':'工作区','danger-full-access':'完全访问'},
    serviceTier: {'standard':'标准','fast':'Fast'}
  };
  let toastTimer = null;

  function markdown(text) {
    const blocks=[];
    let source=esc(text||'').replace(/```([^\n]*)\n([\s\S]*?)```/g,(_,lang,code)=>{const id=blocks.length;blocks.push(`<div class="code-block"><div class="code-lang">${lang||'text'}</div><button class="copy-code" data-copy="${attr(code)}" title="复制">${icon('copy')}</button><pre>${code}</pre></div>`);return `\n§§BLOCK${id}§§\n`;});
    source=source.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)]\((https?:\/\/[^)]+)\)/g,'<a href="$2">$1</a>');
    return `<div class="markdown">${source.split(/\n{2,}/).map(part=>{const token=part.trim().match(/^§§BLOCK(\d+)§§$/);if(token)return blocks[Number(token[1])];if(/^(?:[-*] .+(?:\n|$))+/.test(part.trim()))return '<ul>'+part.trim().split('\n').map(line=>`<li>${line.replace(/^[-*] /,'')}</li>`).join('')+'</ul>';return part.trim()?`<p>${part.replace(/\n/g,'<br>')}</p>`:'';}).join('')}</div>`;
  }

  function header() {
    const secondary=state.view!=='chat', title=state.view==='history'?'历史会话':state.view==='settings'?'设置':state.title;
    return `<header class="header"><div class="header-left">${secondary?`<button class="icon-btn back" data-action="back">${icon('back')}<span>返回</span></button>`:''}<div class="session-wrap"><div class="session-title">${esc(title)}</div>${!secondary&&state.threadId?`<button class="icon-btn title-edit" data-action="rename" title="重命名">${icon('edit')}</button>`:''}</div></div><div class="header-right"><button class="icon-btn" data-action="new" title="新会话">${icon('plus')}</button>${!secondary?`<button class="icon-btn" data-action="conversationSearch" title="搜索">${icon('search')}</button>`:''}<button class="icon-btn" data-action="history" title="历史会话">${icon('history')}</button><button class="icon-btn" data-action="settings" title="设置">${icon('settings')}</button></div></header>`;
  }

  function messageView(entry,index) {
    const kind=entry.kind||'assistant';
    if(kind==='user')return `<article class="message user" data-message="${index}"><div class="message-meta">你</div><div class="message-body">${esc(entry.body)}</div></article>`;
    if(kind==='assistant')return `<article class="message assistant" data-message="${index}"><div class="message-body">${markdown(entry.body)}</div></article>`;
    if(kind==='notice')return `<article class="message notice" data-message="${index}">${esc(entry.title)}${entry.body?` · ${esc(entry.body)}`:''}</article>`;
    const names={reasoning:'推理',plan:'计划',command:'命令',mcp:'MCP 工具',error:'错误'};
    return `<article class="message tool ${kind}" data-message="${index}"><div class="tool-card"><div class="tool-head"><span class="tool-kind">${esc(names[kind]||entry.title||'Codex')}</span><span>${esc(entry.title&&entry.title!==names[kind]?entry.title:'')}</span></div><div class="tool-body">${esc(entry.body)}</div></div></article>`;
  }

  function messagesView() {
    if(!state.messages.length)return `<div class="messages" id="messages"><div class="welcome"><div class="welcome-mark">${icon('codex')}</div><h2>Codex</h2><p>Codex CLI 的原生 JetBrains 工作台。没有供应商切换，也不会注入第三方增强提示词。</p></div></div>`;
    const rail=state.messages.length>2;
    return `${rail?`<div class="anchor-rail"><div class="anchor-track"></div>${state.messages.map((m,i)=>`<button class="anchor-dot" style="top:${((i+.5)/state.messages.length)*100}%" data-anchor="${i}" title="${attr((m.body||m.title||'').slice(0,80))}"></button>`).join('')}</div>`:''}<div class="messages${rail?' has-rail':''}" id="messages">${state.messages.map(messageView).join('')}</div>`;
  }

  function changeStats(change){let plus=0,minus=0;(change.diff||'').split('\n').forEach(line=>{if(line.startsWith('+')&&!line.startsWith('+++'))plus++;if(line.startsWith('-')&&!line.startsWith('---'))minus++;});return{plus,minus};}
  function statusPanel(){const totals=state.changes.reduce((sum,c)=>{const x=changeStats(c);sum.plus+=x.plus;sum.minus+=x.minus;return sum;},{plus:0,minus:0});let pop='';if(state.statusOpen==='changes')pop=`<div class="status-popover"><div class="status-popover-head"><strong>待处理修改</strong><div class="status-actions"><button class="text-btn" data-action="acceptAll" ${state.changes.length?'':'disabled'}>全部接受</button><button class="text-btn danger" data-action="revertAll" ${state.changes.length?'':'disabled'}>全部撤销</button></div></div><div class="change-list">${state.changes.length?state.changes.map((c,i)=>{const s=changeStats(c),kind=(c.kind||'modified').toLowerCase(),mark=kind==='added'?'A':kind==='deleted'?'D':'M';return `<div class="change-row"><span class="change-kind ${kind}">${mark}</span><span class="change-name" data-open-change="${i}" title="${attr(c.path)}">${esc(c.path)}</span><span class="change-stats"><b class="plus">+${s.plus}</b><b class="minus">-${s.minus}</b></span><span class="change-buttons"><button class="mini-btn" data-accept="${i}" title="接受">✓</button><button class="mini-btn" data-revert="${i}" title="撤销">↶</button></span></div>`;}).join(''):'<div class="empty-panel">当前没有待处理文件修改</div>'}</div></div>`;if(state.statusOpen==='tasks')pop='<div class="status-popover"><div class="status-popover-head"><strong>Codex 任务</strong></div><div class="empty-panel">计划与工具执行状态会显示在消息时间线中</div></div>';return `<div class="status-panel">${pop}<div class="status-tabs"><button class="status-tab${state.statusOpen==='tasks'?' active':''}" data-status="tasks">${icon('branch')}<span>任务</span></button><button class="status-tab${state.statusOpen==='changes'?' active':''}" data-status="changes">${icon('code')}<span>修改 ${state.changes.length}</span><span class="change-stats"><b class="plus">+${totals.plus}</b><b class="minus">-${totals.minus}</b></span></button></div></div>`;}

  function selector(name,value,items,iconName,title){const open=state.openMenu===name;return `<div class="selector-shell"><button class="selector-button ${name==='approval'&&value==='never'?'automatic':''}" data-menu="${name}" title="${attr(title)}">${icon(iconName)}<span class="selector-button-text">${esc((labels[name]||{})[value]||value||'默认')}</span>${icon('down')}</button>${open?`<div class="selector-menu">${items.map(item=>`<button class="selector-option${item===value?' selected':''}" data-choice="${name}" data-value="${attr(item)}"><span>${esc((labels[name]||{})[item]||item||'默认')}</span>${item===value?icon('check'):''}</button>`).join('')}</div>`:''}</div>`;}
  function approvalSelector(){const choices=[['untrusted','chat','谨慎模式','最安全的选择，每一步都需要你亲自批准。'],['on-request','robot','自动编辑','保持正常编辑流程，仅在需要时进行审批。'],['never','bolt','全自动','文件和执行命令立即生效，仅受沙箱限制。']];const open=state.openMenu==='approval';return `<div class="selector-shell approval-shell"><button class="selector-button ${state.approval==='never'?'automatic':''}" data-menu="approval" title="审批模式">${icon('bolt')}<span class="selector-button-text">${esc(labels.approval[state.approval]||'按需审批')}</span>${icon('down')}</button>${open?`<div class="selector-menu approval-menu">${choices.map(([value,ico,title,description])=>`<button class="approval-option${state.approval===value?' selected':''}" data-choice="approval" data-value="${value}"><span class="approval-icon">${icon(ico)}</span><span class="approval-copy"><b>${title}</b><small>${description}</small></span>${state.approval===value?icon('check'):''}</button>`).join('')}</div>`:''}</div>`;}
  function toggleRow(iconName,title,description,on,action){return `<button class="config-row" data-action="${action}"><span class="config-icon">${icon(iconName)}</span><span class="config-copy"><b>${title}</b>${description?`<small>${description}</small>`:''}</span><span class="switch ${on?'on':''}" aria-hidden="true"></span></button>`;}
  function composerSubmenu(){if(state.composerSubmenu==='prompts'){const items=state.prompts.map(prompt=>`<button class="submenu-option${state.activePromptId===prompt.id?' selected':''}" data-prompt-select="${attr(prompt.id)}"><span class="config-icon">${icon('robot')}</span><span class="config-copy"><b>${esc(prompt.name)}</b><small>${esc(prompt.description||prompt.instructions)}</small></span>${state.activePromptId===prompt.id?icon('check'):''}</button>`).join('');return `<div class="composer-submenu"><div class="submenu-list">${items||'<div class="submenu-empty">还没有保存的提示词</div>'}</div><button class="submenu-create" data-settings-go="instructions">${icon('plus')}<span><b>创建提示词</b><small>前往提示词库新增</small></span></button></div>`;}if(state.composerSubmenu==='agents'){const items=`<button class="submenu-option${state.activeAgentId?'':' selected'}" data-agent-select=""><span class="config-icon">${icon('codex')}</span><span class="config-copy"><b>默认身份</b><small>不添加 Agent 身份指令</small></span>${state.activeAgentId?'':icon('check')}</button>`+state.agents.map(agent=>`<button class="submenu-option${state.activeAgentId===agent.id?' selected':''}" data-agent-select="${attr(agent.id)}"><span class="config-icon">${icon('robot')}</span><span class="config-copy"><b>${esc(agent.name)}</b><small>${esc(agent.instructions)}</small></span>${state.activeAgentId===agent.id?icon('check'):''}</button>`).join('');return `<div class="composer-submenu"><div class="submenu-list">${items}</div><button class="submenu-create" data-settings-go="agents">${icon('plus')}<span><b>管理 Agent 身份</b><small>前往设置进行新建和编辑</small></span></button></div>`;}if(state.composerSubmenu==='process')return `<div class="composer-submenu process-submenu"><div class="process-status"><span class="process-dot ${state.connected?'online':''}"></span><span><b>${state.connected?'Codex CLI 已连接':'Codex CLI 未连接'}</b><small>${state.connected?'1 个本地 app-server 进程':'可尝试重新启动本地进程'}</small></span></div><button class="submenu-create" data-action="reconnect">${icon('server')}<span><b>重新连接</b><small>重启 Codex CLI 进程</small></span></button></div>`;return'';}
  function composerMenu(){if(!state.composerMenu)return'';const agent=state.agents.find(item=>item.id===state.activeAgentId),prompt=state.prompts.find(item=>item.id===state.activePromptId);return `<div class="composer-menu-shell"><div class="composer-menu"><button class="config-row${state.composerSubmenu==='prompts'?' active':''}" data-composer-submenu="prompts"><span class="config-icon">${icon('note')}</span><span class="config-copy"><b>提示词</b><small>${esc(prompt?.name||'未启用')}</small></span>${icon('chevron')}</button><button class="config-row${state.composerSubmenu==='agents'?' active':''}" data-composer-submenu="agents"><span class="config-icon">${icon('robot')}</span><span class="config-copy"><b>Agent 身份</b><small>${esc(agent?.name||'未启用')}</small></span>${icon('chevron')}</button><div class="menu-divider"></div><button class="config-row${state.composerSubmenu==='process'?' active':''}" data-composer-submenu="process"><span class="config-icon">${icon('server')}</span><span class="config-copy"><b>Codex CLI 进程</b><small>${state.connected?'1 个进程 · 已连接':'未连接'}</small></span>${icon('chevron')}</button><div class="menu-divider"></div>${toggleRow('code','流式传输','',state.streamResponses,'toggleStreaming')}${toggleRow('bulb','思考过程','',state.showReasoning,'toggleReasoning')}</div>${composerSubmenu()}</div>`;}
  function composer(){const modelItems=state.models.length?state.models:[''];return `<div class="input-area"><div class="composer"><div class="context-row">${state.attachments.length?state.attachments.map((a,i)=>`<span class="chip"><b>${a.kind==='IMAGE'?'图片':a.kind==='SKILL'?'Skill':'文件'}</b><span title="${attr(a.path||a.name)}">${esc(a.name)}</span><button data-remove-attachment="${i}">×</button></span>`).join(''):'<span class="context-placeholder">当前文件与附件会作为 Codex 原生输入发送</span>'}</div><div class="input-wrap"><textarea id="prompt" class="input" placeholder="@ 引用文件，/ 使用 Codex 命令，Enter 发送"></textarea></div><div class="toolbar"><div class="toolbar-left"><span class="toolbar-settings">${composerMenu()}<button class="toolbar-icon" data-action="composerSettings" title="聊天设置">${icon('sliders')}</button></span>${approvalSelector()}${selector('model',state.model,modelItems,'codex','模型')}${selector('effort',state.effort,['minimal','low','medium','high','xhigh','ultra'],'bulb','推理强度')}${selector('serviceTier',state.serviceTier,['standard','fast'],state.serviceTier==='fast'?'bolt':'code','响应模式')}${selector('sandbox',state.sandbox,['read-only','workspace-write','danger-full-access'],'code','工作区权限')}</div><div class="toolbar-right"><button class="icon-btn" data-action="pickFile" title="引用文件">${icon('paperclip')}</button><button class="icon-btn" data-action="pickImage" title="添加图片">${icon('image')}</button><button class="icon-btn" data-action="pickSkill" title="添加 Skill">${icon('spark')}</button>${state.busy?`<button class="submit stop" data-action="stop" title="停止">${icon('stop')}</button>`:`<button class="submit" data-action="send" title="发送">${icon('send')}</button>`}</div></div></div></div>`;}
  function chatPage(){return `<main class="chat-page"><div class="messages-shell">${messagesView()}</div>${statusPanel()}${composer()}</main>`;}
  function historyPage(){return `<main class="page"><div class="page-toolbar"><input id="historySearch" class="search" value="${attr(state.historySearch)}" placeholder="搜索历史会话"><button class="text-btn" data-action="export">导出当前会话</button></div><div class="history-list">${state.history.length?state.history.map(h=>`<div class="history-item" data-thread="${attr(h.id)}"><div class="history-main"><span class="history-title">${h.favorite?'<span class="favorite">★</span>':''}${esc(h.title)}</span><span class="history-time">${esc(h.time||'')}</span></div><div class="history-meta">Codex CLI 会话 · ${esc(h.id.slice(0,12))}</div></div>`).join(''):'<div class="empty-panel">没有匹配的历史会话</div>'}</div></main>`;}

  const settingsTabs=[['basic','settings','基础设置'],['instructions','note','提示词库'],['agents','robot','Agent 身份'],['skills','spark','Skills'],['mcp','server','MCP']];
  function settingDropdown(name,value,items){return `<div class="setting-selector">${selector(name,value,items,'down',name)}</div>`;}
  function settingRow(label,hint,control){return `<div class="setting-row"><div><div class="setting-label">${label}</div><div class="setting-hint">${hint}</div></div><div class="setting-value">${control}</div></div>`;}
  function basicSettings(){return `<section class="settings-content-section"><div class="section-heading"><h2>基础设置</h2><p>直接映射 Codex CLI 原生会话参数。</p></div><div class="settings-card">${settingRow('默认模型','模型列表来自当前 Codex CLI',settingDropdown('model',state.model,state.models.length?state.models:['']))}${settingRow('推理强度','控制 Codex 的原生推理强度',settingDropdown('effort',state.effort,['minimal','low','medium','high','xhigh','ultra']))}${settingRow('响应模式','Fast 使用 Codex 的快速服务档位',settingDropdown('serviceTier',state.serviceTier,['standard','fast']))}${settingRow('审批模式','“全自动”不会再弹出命令和文件审批',settingDropdown('approval',state.approval,['untrusted','on-request','never']))}${settingRow('工作区权限','控制 Codex 可读取和写入的范围',settingDropdown('sandbox',state.sandbox,['read-only','workspace-write','danger-full-access']))}${settingRow('流式传输','打开时实时显示 Codex 输出',`<button class="switch ${state.streamResponses?'on':''}" data-action="toggleStreaming"></button>`)}${settingRow('思考过程','显示 Codex 返回的推理摘要',`<button class="switch ${state.showReasoning?'on':''}" data-action="toggleReasoning"></button>`)}</div><div class="settings-card">${settingRow('会话操作','由 Codex app-server 原生处理',`<div class="button-group"><button class="text-btn" data-action="compact">压缩上下文</button><button class="text-btn" data-action="review">审查修改</button><button class="text-btn danger" data-action="rewind">回退一轮</button></div>`)}${settingRow('账户用量','读取当前 Codex 登录账户',`<button class="text-btn" data-action="usage">查看用量</button>`)}</div></section>`;}
  function instructionsSettings(){const prompts=state.prompts.map(prompt=>`<div class="prompt-card ${state.activePromptId===prompt.id?'active':''}"><button class="prompt-main" data-prompt-select="${attr(prompt.id)}"><span class="prompt-avatar">${icon('note')}</span><span class="prompt-info"><b>${esc(prompt.name)}</b><small>${esc(prompt.description||prompt.instructions)}</small></span>${state.activePromptId===prompt.id?icon('check'):''}</button><button class="card-action" data-prompt-edit="${attr(prompt.id)}" title="编辑">${icon('edit')}</button><button class="card-action danger" data-prompt-delete="${attr(prompt.id)}" title="删除">${icon('trash')}</button></div>`).join('');return `<section class="settings-content-section"><div class="section-heading action-heading"><div><h2>提示词库</h2><p>启用的提示词通过 Codex 原生 developer instructions 应用于之后的新会话。</p></div><button class="primary-btn" data-action="newPrompt">＋ 新建提示词</button></div><div class="prompt-list"><button class="prompt-card ${state.activePromptId?'':'active'}" data-prompt-select=""><span class="prompt-avatar">${icon('codex')}</span><span class="prompt-info"><b>不使用库内提示词</b><small>仅应用下方的全局与项目指令</small></span>${state.activePromptId?'':icon('check')}</button>${prompts}</div><div class="subsection-heading"><h3>基础指令</h3><p>全局和项目指令会与当前启用的库内提示词合并。</p></div><div class="editor-card"><label>全局提示词<span>适用于所有项目</span></label><textarea id="globalInstructions" class="large-input" placeholder="例如：始终使用中文回复">${esc(state.globalInstructions)}</textarea></div><div class="editor-card"><label>项目提示词<span>仅保存到当前项目的工作区配置</span></label><textarea id="projectInstructions" class="large-input" placeholder="例如：遵循本项目的目录和测试约定">${esc(state.projectInstructions)}</textarea></div><div class="settings-actions"><button class="primary-btn" data-action="saveInstructions">保存基础指令</button></div></section>`;}
  function agentsSettings(){return `<section class="settings-content-section"><div class="section-heading action-heading"><div><h2>Agent 身份</h2><p>选择一个身份后，它的指令会用于之后创建的新会话。</p></div><button class="primary-btn" data-action="newAgent">＋ 新建 Agent</button></div><div class="agent-list"><button class="agent-card ${!state.activeAgentId?'active':''}" data-agent-select=""><span class="agent-avatar">${icon('codex')}</span><span class="agent-info"><b>默认 Codex</b><small>不添加 Agent 身份指令</small></span>${!state.activeAgentId?icon('check'):''}</button>${state.agents.map(agent=>`<div class="agent-card ${state.activeAgentId===agent.id?'active':''}"><button class="agent-main" data-agent-select="${attr(agent.id)}"><span class="agent-avatar">${icon('robot')}</span><span class="agent-info"><b>${esc(agent.name)}</b><small>${esc(agent.instructions.slice(0,90))}${agent.instructions.length>90?'…':''}</small></span>${state.activeAgentId===agent.id?icon('check'):''}</button><button class="card-action" data-agent-edit="${attr(agent.id)}" title="编辑">${icon('edit')}</button><button class="card-action danger" data-agent-delete="${attr(agent.id)}" title="删除">${icon('trash')}</button></div>`).join('')}</div></section>`;}
  function mcpSettings(){
    const items=state.mcpServers.map(server=>{
      const name=server.name||server.id||'未命名服务器';
      const status=server.authStatus==='oAuth'?'OAuth 已登录':server.authStatus==='bearerToken'?'令牌已配置':server.authStatus==='notLoggedIn'?'需要登录':'已配置';
      const tools=Array.isArray(server.tools)?server.tools.length:Object.keys(server.tools||{}).length;
      return `<div class="mcp-card"><span class="mcp-icon">${icon('server')}</span><span class="mcp-info"><b>${esc(name)}</b><small>${esc(typeof status==='string'?status:JSON.stringify(status))}</small></span><span class="mcp-tools">${tools} 个工具</span></div>`;
    }).join('');
    const empty=`<div class="settings-empty"><span>${icon('server')}</span><b>没有已配置的 MCP 服务器</b><small>点击“打开配置”编辑 ~/.codex/config.toml，然后重新加载。</small></div>`;
    return `<section class="settings-content-section"><div class="section-heading action-heading"><div><h2>MCP 服务器</h2><p>只读取 Codex CLI 的 MCP 配置，不维护任何其它供应商。</p></div><div class="button-group"><button class="text-btn" data-action="openMcpConfig">打开配置</button><button class="primary-btn" data-action="reloadMcp">重新加载</button></div></div><div class="mcp-list">${items||empty}</div></section>`;
  }
  function skillsSettings(){const query=state.skillSearch.trim().toLowerCase(),skills=state.skills.filter(skill=>!query||`${skill.name} ${skill.description} ${skill.path}`.toLowerCase().includes(query));const items=skills.map(skill=>`<div class="skill-card"><span class="skill-icon">${icon('spark')}</span><span class="skill-info"><b>${esc(skill.name)}</b><small>${esc(skill.description||'无说明')}</small><code title="${attr(skill.path)}">${esc(skill.path)}</code></span><button class="text-btn" data-skill-attach="${attr(skill.path)}" data-skill-name="${attr(skill.name)}">附加</button></div>`).join('');return `<section class="settings-content-section"><div class="section-heading action-heading"><div><h2>Skills</h2><p>浏览 Codex CLI 在当前工作区发现的 Skills，并附加到下一条消息。</p></div><button class="primary-btn" data-action="reloadSkills">重新加载</button></div><div class="skills-toolbar"><input id="skillSearch" class="search" value="${attr(state.skillSearch)}" placeholder="搜索 Skill"></div><div class="skill-list">${items||`<div class="settings-empty"><span>${icon('spark')}</span><b>${state.skills.length?'没有匹配的 Skill':'当前工作区没有可用的 Skill'}</b><small>${state.skills.length?'请尝试其它关键词':'Codex 会从用户与项目 Skills 目录中自动发现。'}</small></div>`}</div></section>`;}
  function settingsPage(){const content=state.settingsTab==='instructions'?instructionsSettings():state.settingsTab==='agents'?agentsSettings():state.settingsTab==='skills'?skillsSettings():state.settingsTab==='mcp'?mcpSettings():basicSettings();return `<main class="settings-page"><aside class="settings-sidebar">${settingsTabs.map(([key,ico,label])=>`<button class="settings-nav ${state.settingsTab===key?'active':''}" data-settings-tab="${key}">${icon(ico)}<span>${label}</span></button>`).join('')}</aside><div class="settings-content">${content}</div></main>`;}

  function agentDialog(){if(!state.agentEditor)return'';const agent=state.agentEditor;return `<div class="modal-overlay"><div class="modal-card agent-dialog"><div class="modal-heading"><div><h3>${agent.id?'编辑 Agent':'新建 Agent'}</h3><p>身份指令由你管理，并以 Codex 原生指令传入新会话。</p></div></div><label class="form-label">名称<input id="agentName" class="text-input" value="${attr(agent.name||'')}" placeholder="例如：代码审查员"></label><label class="form-label">身份指令<textarea id="agentInstructions" class="large-input" placeholder="描述角色、职责和工作约束">${esc(agent.instructions||'')}</textarea></label><div class="modal-actions"><button class="text-btn" data-action="closeAgent">取消</button><button class="primary-btn" data-action="saveAgent">保存</button></div></div></div>`;}
  function promptDialog(){if(!state.promptEditor)return'';const prompt=state.promptEditor;return `<div class="modal-overlay"><div class="modal-card prompt-dialog"><div class="modal-heading"><div><h3>${prompt.id?'编辑提示词':'新建提示词'}</h3><p>保存后可从聊天输入区快速启用，并在新会话中生效。</p></div></div><label class="form-label">名称<input id="promptName" class="text-input" value="${attr(prompt.name||'')}" placeholder="例如：程序"></label><label class="form-label">简短说明<input id="promptDescription" class="text-input" value="${attr(prompt.description||'')}" placeholder="说明这个提示词适合处理什么任务"></label><label class="form-label">提示词内容<textarea id="promptInstructions" class="large-input" placeholder="描述职责、工作方式和约束">${esc(prompt.instructions||'')}</textarea></label><div class="modal-actions"><button class="text-btn" data-action="closePrompt">取消</button><button class="primary-btn" data-action="savePrompt">保存</button></div></div></div>`;}
  function questionDialog(){if(!state.question)return'';const questions=state.question.questions||[],index=Math.max(0,Math.min(state.questionIndex,questions.length-1)),q=questions[index];if(!q)return'';const answer=state.questionAnswers[q.id]||{values:[],other:''},selected=answer.values[0]||'',options=Array.isArray(q.options)?q.options:[];return `<div class="modal-overlay question-overlay"><div class="modal-card question-dialog"><div class="modal-heading"><div><h3>Codex 有一些问题想问你</h3><p>不会自动关闭，你可以仔细比较每个方案。</p></div><span class="question-progress">${index+1} / ${questions.length}</span></div><div class="question-header"><span>${esc(q.header||'需要选择')}</span><p>${esc(q.question||'')}</p></div><div class="question-options">${options.map(option=>`<button class="question-option ${selected===option.label?'selected':''}" data-question-option="${attr(q.id)}" data-value="${attr(option.label)}"><span class="choice-mark">${selected===option.label?icon('check'):''}</span><span><b>${esc(option.label)}</b><small>${esc(option.description||'')}</small></span></button>`).join('')}${q.isOther?`<button class="question-option ${selected==='__other__'?'selected':''}" data-question-option="${attr(q.id)}" data-value="__other__"><span class="choice-mark">${selected==='__other__'?icon('check'):''}</span><span><b>其它</b><small>输入你自己的方案或补充细节</small></span></button>`:''}</div>${(!options.length||selected==='__other__')?`<textarea id="questionOther" class="large-input question-other${q.isSecret?' secret-input':''}" placeholder="请输入详细答案">${esc(answer.other||'')}</textarea>`:''}<div class="modal-actions"><button class="text-btn" data-action="cancelQuestions">取消</button>${index>0?'<button class="text-btn" data-action="questionBack">上一步</button>':''}<button class="primary-btn" data-action="questionNext">${index===questions.length-1?'提交':'下一步'}</button></div></div></div>`;}

  function render(preservePrompt=true){const oldPrompt=preservePrompt?document.getElementById('prompt')?.value||'':'';root.innerHTML=`<div class="app">${header()}${state.view==='chat'?chatPage():state.view==='history'?historyPage():settingsPage()}</div>${agentDialog()}${promptDialog()}${questionDialog()}${state.toast?`<div class="toast">${esc(state.toast)}</div>`:''}`;const prompt=document.getElementById('prompt');if(prompt){prompt.value=oldPrompt;resizePrompt(prompt);}bind();}
  function showToast(message,duration=2200){state.toast=message||'';clearTimeout(toastTimer);if(state.toast)toastTimer=setTimeout(()=>{if(state.toast===message){state.toast='';render();}},duration);}
  function resizePrompt(el){el.style.height='auto';el.style.height=Math.min(240,Math.max(84,el.scrollHeight))+'px';}
  function sendPrompt(){const prompt=document.getElementById('prompt'),text=prompt?.value.trim()||'';if(state.busy||(!text&&!state.attachments.length))return;post('send',{text});if(prompt)prompt.value='';}
  function storeQuestionText(){const q=state.question?.questions?.[state.questionIndex],input=document.getElementById('questionOther');if(q&&input){const current=state.questionAnswers[q.id]||{values:[],other:''};current.other=input.value;state.questionAnswers[q.id]=current;}}
  function questionReady(q){const answer=state.questionAnswers[q.id]||{values:[],other:''};if(!Array.isArray(q.options)||!q.options.length)return !!answer.other.trim();if(answer.values[0]==='__other__')return !!answer.other.trim();return !!answer.values[0];}
  function submitQuestions(){const answers={};for(const q of state.question.questions||[]){const value=state.questionAnswers[q.id]||{values:[],other:''};const selected=value.values[0]==='__other__'?value.other.trim():value.values[0]||(value.other||'').trim();answers[q.id]={answers:selected?[selected]:[]};}post('answerQuestions',{requestId:state.question.requestId,answers});state.question=null;state.questionAnswers={};render();}

  function bind(){
    root.querySelectorAll('[data-action]').forEach(el=>el.onclick=e=>{e.stopPropagation();const action=el.dataset.action;
      if(action==='back'){state.view='chat';render();return;}if(action==='history'){state.view='history';post('history',{search:state.historySearch});render();return;}if(action==='settings'){state.view='settings';render();return;}if(action==='send'){sendPrompt();return;}if(action==='composerSettings'){state.composerMenu=!state.composerMenu;state.composerSubmenu=null;state.openMenu=null;render();return;}if(action==='toggleReasoning'){post('toggleReasoning');return;}if(action==='toggleStreaming'){post('toggleStreaming');return;}
      if(action==='saveInstructions'){post('saveInstructions',{global:document.getElementById('globalInstructions')?.value||'',project:document.getElementById('projectInstructions')?.value||''});return;}if(action==='newAgent'){state.agentEditor={id:'',name:'',instructions:''};render();return;}if(action==='closeAgent'){state.agentEditor=null;render();return;}if(action==='saveAgent'){post('saveAgent',{id:state.agentEditor.id,name:document.getElementById('agentName')?.value||'',instructions:document.getElementById('agentInstructions')?.value||''});state.agentEditor=null;return;}if(action==='newPrompt'){state.promptEditor={id:'',name:'',description:'',instructions:''};render();return;}if(action==='closePrompt'){state.promptEditor=null;render();return;}if(action==='savePrompt'){post('savePrompt',{id:state.promptEditor.id,name:document.getElementById('promptName')?.value||'',description:document.getElementById('promptDescription')?.value||'',instructions:document.getElementById('promptInstructions')?.value||''});state.promptEditor=null;return;}
      if(action==='cancelQuestions'){post('cancelQuestions',{requestId:state.question.requestId});state.question=null;render();return;}if(action==='questionBack'){storeQuestionText();state.questionIndex=Math.max(0,state.questionIndex-1);render();return;}if(action==='questionNext'){storeQuestionText();const q=state.question.questions[state.questionIndex];if(!questionReady(q)){showToast('请选择一个方案或填写详细答案');render();return;}if(state.questionIndex<state.question.questions.length-1){state.questionIndex++;render();}else submitQuestions();return;}if(action==='reconnect'){state.composerMenu=false;state.composerSubmenu=null;post('reconnect');render();return;}if((action==='acceptAll'||action==='revertAll')&&!state.changes.length){state.statusOpen=null;showToast('当前没有待处理的文件修改');render();return;}post(action);
    });
    root.querySelectorAll('[data-menu]').forEach(el=>el.onclick=e=>{e.stopPropagation();state.openMenu=state.openMenu===el.dataset.menu?null:el.dataset.menu;state.composerMenu=false;state.composerSubmenu=null;render();});root.querySelectorAll('[data-choice]').forEach(el=>el.onclick=e=>{e.stopPropagation();const key=el.dataset.choice,value=el.dataset.value;state[key]=value;state.openMenu=null;post('setting',{key,value});render();});root.querySelectorAll('[data-composer-submenu]').forEach(el=>el.onclick=e=>{e.stopPropagation();state.composerSubmenu=state.composerSubmenu===el.dataset.composerSubmenu?null:el.dataset.composerSubmenu;render();});
    root.querySelectorAll('[data-settings-tab]').forEach(el=>el.onclick=()=>{state.settingsTab=el.dataset.settingsTab;if(state.settingsTab==='mcp')post('loadMcp');if(state.settingsTab==='skills')post('loadSkills');render();});root.querySelectorAll('[data-settings-go]').forEach(el=>el.onclick=()=>{state.view='settings';state.settingsTab=el.dataset.settingsGo;state.composerMenu=false;state.composerSubmenu=null;if(state.settingsTab==='mcp')post('loadMcp');if(state.settingsTab==='skills')post('loadSkills');render();});root.querySelectorAll('[data-status]').forEach(el=>el.onclick=()=>{state.statusOpen=state.statusOpen===el.dataset.status?null:el.dataset.status;render();});
    root.querySelectorAll('[data-thread]').forEach(el=>el.onclick=()=>post('openThread',{id:el.dataset.thread}));root.querySelectorAll('[data-anchor]').forEach(el=>el.onclick=()=>document.querySelector(`[data-message="${el.dataset.anchor}"]`)?.scrollIntoView({behavior:'smooth',block:'start'}));root.querySelectorAll('[data-open-change]').forEach(el=>el.onclick=()=>post('openChange',{index:Number(el.dataset.openChange)}));root.querySelectorAll('[data-accept]').forEach(el=>el.onclick=()=>post('acceptChange',{index:Number(el.dataset.accept)}));root.querySelectorAll('[data-revert]').forEach(el=>el.onclick=()=>post('revertChange',{index:Number(el.dataset.revert)}));root.querySelectorAll('[data-remove-attachment]').forEach(el=>el.onclick=()=>post('removeAttachment',{index:Number(el.dataset.removeAttachment)}));
    root.querySelectorAll('[data-agent-select]').forEach(el=>el.onclick=()=>post('selectAgent',{id:el.dataset.agentSelect||''}));root.querySelectorAll('[data-agent-edit]').forEach(el=>el.onclick=()=>{const agent=state.agents.find(item=>item.id===el.dataset.agentEdit);if(agent){state.agentEditor={...agent};render();}});root.querySelectorAll('[data-agent-delete]').forEach(el=>el.onclick=()=>post('deleteAgent',{id:el.dataset.agentDelete}));root.querySelectorAll('[data-prompt-select]').forEach(el=>el.onclick=()=>post('selectPrompt',{id:el.dataset.promptSelect||''}));root.querySelectorAll('[data-prompt-edit]').forEach(el=>el.onclick=()=>{const prompt=state.prompts.find(item=>item.id===el.dataset.promptEdit);if(prompt){state.promptEditor={...prompt};render();}});root.querySelectorAll('[data-prompt-delete]').forEach(el=>el.onclick=()=>post('deletePrompt',{id:el.dataset.promptDelete}));root.querySelectorAll('[data-skill-attach]').forEach(el=>el.onclick=()=>post('attachSkill',{name:el.dataset.skillName||'',path:el.dataset.skillAttach||''}));root.querySelectorAll('[data-question-option]').forEach(el=>el.onclick=()=>{storeQuestionText();state.questionAnswers[el.dataset.questionOption]={values:[el.dataset.value],other:state.questionAnswers[el.dataset.questionOption]?.other||''};render();});
    root.querySelectorAll('[data-copy]').forEach(el=>el.onclick=()=>navigator.clipboard.writeText(el.dataset.copy||''));root.querySelectorAll('a').forEach(el=>el.onclick=e=>{e.preventDefault();post('openUrl',{url:el.href});});const prompt=document.getElementById('prompt');if(prompt){prompt.oninput=()=>resizePrompt(prompt);prompt.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();sendPrompt();}};}const history=document.getElementById('historySearch');if(history){let timer;history.oninput=()=>{state.historySearch=history.value;clearTimeout(timer);timer=setTimeout(()=>post('history',{search:history.value}),180);};}const skillSearch=document.getElementById('skillSearch');if(skillSearch)skillSearch.oninput=()=>{state.skillSearch=skillSearch.value;render();};root.onclick=()=>{if(state.openMenu||state.composerMenu){state.openMenu=null;state.composerMenu=false;state.composerSubmenu=null;render();}};
  }
  function scrollBottom(){const el=document.getElementById('messages');if(el)requestAnimationFrame(()=>el.scrollTop=el.scrollHeight);}
  window.CodexGui={receive(event){const e=typeof event==='string'?JSON.parse(event):event;switch(e.type){case'bootstrap':Object.assign(state,e.state||{});break;case'connection':state.connected=!!e.connected;if(!e.connected&&e.detail)showToast(e.detail);break;case'busy':state.busy=!!e.busy;break;case'clear':state.messages=[];state.title=e.title||'新会话';state.threadId=e.threadId||null;break;case'message':state.messages.push(e.entry);break;case'replaceMessage':{const i=state.messages.findIndex(m=>m.itemId===e.entry.itemId);if(i>=0)state.messages[i]=e.entry;else state.messages.push(e.entry);break;}case'history':state.history=e.items||[];break;case'changes':state.changes=e.items||[];break;case'attachments':state.attachments=e.items||[];break;case'thread':state.threadId=e.id||null;state.title=e.title||state.title;state.view='chat';break;case'mcpServers':state.mcpServers=e.items||[];break;case'skills':state.skills=e.items||[];break;case'question':state.question={requestId:e.requestId,questions:e.questions||[]};state.questionIndex=0;state.questionAnswers={};break;case'toast':showToast(e.message||'');break;}render();if(['message','replaceMessage','clear'].includes(e.type))scrollBottom();}};
  render(false);post('ready');
})();
