(() => {
  const readPreference = (key, fallback) => {
    try { return localStorage.getItem(`codex-gui.${key}`) ?? fallback; } catch (_) { return fallback; }
  };
  const state = {
    view: 'chat', connected: false, busy: false, title: '新会话', threadId: null,
    messages: [], history: [], changes: [], attachments: [], models: [], mcpServers: [], skills: [], skillErrors: [],
    model: '', effort: 'high', approval: 'on-request', sandbox: 'workspace-write', serviceTier: 'standard',
    streamResponses: true, showReasoning: true, globalInstructions: '', projectInstructions: '',
    sendShortcut: 'enter', permissionDialogTimeoutSeconds: 300, sendOpenedFilePath: true, diffExpandedByDefault: false,
    newSessionConfirmEnabled: true, askUserQuestionNotificationEnabled: false, askUserQuestionSoundEnabled: false,
    taskCompletionNotificationEnabled: false, taskCompletionSoundEnabled: false, systemNotificationOnlyWhenUnfocused: false,
    soundOnlyWhenUnfocused: false, notificationSound: 'default', customSoundPath: '', soundMenuOpen: false,
    agents: [], activeAgentId: '', prompts: [], activePromptId: '', statusOpen: null, statusPanelExpanded: true, openMenu: null,
    composerMenu: false, composerSubmenu: null, fileContextPrompt: false,
    activeFile: '', usagePercentage: 0, usageUsedTokens: 0, usageMaxTokens: 0,
    settingsTab: 'basic', basicSettingsTab: 'appearance', historySearch: '', toast: '', question: null, questionIndex: 0,
    appearanceTheme: readPreference('theme','system'), appearanceScale: Number(readPreference('scale','100')) || 100,
    chatBgColor: readPreference('chat-bg',''), chatBarColor: readPreference('chat-bar',''), userMsgColor: readPreference('user-message',''),
    questionAnswers: {}, agentEditor: null, promptEditor: null,
    skillSearch: '', skillScope: 'all', skillStatus: 'all', selectedSkillPath: '', skillImportOpen: false,
    expandedMcpName: '', mcpAddOpen: false, mcpEditor: null, mcpDeleteName: '',
    mcpHelp: false, mcpLogsOpen: false, mcpActivity: []
  };
  const root = document.getElementById('app');

  const icons = {
    plus: '<path d="M12 5v14M5 12h14"/>',
    history: '<path d="M3 12a9 9 0 1 0 3-6.7L3 8"/><path d="M3 3v5h5M12 7v5l3 2"/>',
    settings: '<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1A1.7 1.7 0 0 0 9 4.6a1.7 1.7 0 0 0 1-1.6v-.2h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3 1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/>',
    search: '<circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/>',
    edit: '<path d="m4 16-1 5 5-1L19 9l-4-4L4 16Z"/><path d="m13.5 6.5 4 4"/>',
    back: '<path d="m15 18-6-6 6-6"/>',
    paperclip: '<path d="m21 12-8.5 8.5a6 6 0 0 1-8.5-8.5l9-9a4 4 0 0 1 5.7 5.7l-9 9a2 2 0 0 1-2.9-2.8l8.4-8.4"/>',
    image: '<rect x="3" y="4" width="18" height="16" rx="2"/><circle cx="9" cy="10" r="2"/><path d="m21 15-5-5L5 20"/>',
    send: '<path d="m5 12 14-7-4 14-3-6-7-1Z"/><path d="m12 13 7-8"/>',
    stop: '<rect x="7" y="7" width="10" height="10" rx="1"/>',
    branch: '<circle cx="6" cy="5" r="2"/><circle cx="18" cy="6" r="2"/><circle cx="6" cy="19" r="2"/><path d="M6 7v10M8 6h4a6 6 0 0 1 6 6v4"/>',
    code: '<path d="m8 9-3 3 3 3M16 9l3 3-3 3M14 5l-4 14"/>',
    copy: '<rect x="8" y="8" width="11" height="11" rx="2"/><path d="M16 8V5a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v9a2 2 0 0 0 2 2h3"/>',
    spark: '<path d="m12 3 1.3 4.7L18 9l-4.7 1.3L12 15l-1.3-4.7L6 9l4.7-1.3L12 3Z"/>',
    sliders: '<path d="M4 7h10M18 7h2M4 17h2M10 17h10"/><circle cx="16" cy="7" r="2"/><circle cx="8" cy="17" r="2"/>',
    bolt: '<path d="m13 2-8 12h7l-1 8 8-12h-7l1-8Z"/>',
    bulb: '<path d="M9 18h6M10 22h4M8.2 14.7A7 7 0 1 1 15.8 14.7c-.8.7-1.3 1.5-1.3 2.3h-5c0-.8-.5-1.6-1.3-2.3Z"/>',
    robot: '<rect x="5" y="7" width="14" height="11" rx="3"/><path d="M12 3v4M8 12h.01M16 12h.01M9 15h6"/>',
    server: '<rect x="4" y="4" width="16" height="6" rx="2"/><rect x="4" y="14" width="16" height="6" rx="2"/><path d="M8 7h.01M8 17h.01"/>',
    note: '<path d="M6 3h12v18H6zM9 8h6M9 12h6M9 16h4"/>',
    chevron: '<path d="m9 18 6-6-6-6"/>',
    down: '<path d="m7 10 5 5 5-5"/>',
    check: '<path d="m5 12 4 4L19 6"/>',
    trash: '<path d="M4 7h16M9 7V4h6v3M7 7l1 14h8l1-14M10 11v6M14 11v6"/>',
    codex: '<path d="M12 3.2a4.4 4.4 0 0 1 4.2 3.1 4.4 4.4 0 0 1 1.3 8.5 4.4 4.4 0 0 1-7.4 4.6 4.4 4.4 0 0 1-6.3-6.1 4.4 4.4 0 0 1 3.2-7.4A4.4 4.4 0 0 1 12 3.2Z"/><path d="m8.2 8.1 7.6 4.4v4.2M15.8 15.9l-7.6-4.4V7.3M12 18.1V9.3"/>',
    chat: '<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4Z"/>'
    ,refresh: '<path d="M20 6v5h-5M4 18v-5h5"/><path d="M6.1 9a7 7 0 0 1 11.6-2.6L20 11M4 13l2.3 4.6A7 7 0 0 0 17.9 15"/>'
    ,external: '<path d="M14 4h6v6M20 4l-9 9"/><path d="M18 13v6a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1V7a1 1 0 0 1 1-1h6"/>'
    ,question: '<circle cx="12" cy="12" r="9"/><path d="M9.8 9a2.4 2.4 0 1 1 3.3 2.2c-.8.4-1.1.9-1.1 1.8M12 17h.01"/>'
    ,alert: '<circle cx="12" cy="12" r="9"/><path d="M12 7v6M12 17h.01"/>'
    ,close: '<path d="m6 6 12 12M18 6 6 18"/>'
    ,palette: '<path d="M12 3a9 9 0 0 0 0 18h1.4a1.7 1.7 0 0 0 1.2-2.9 1.7 1.7 0 0 1 1.2-2.9H18A3 3 0 0 0 21 12a9 9 0 0 0-9-9Z"/><path d="M7.5 10h.01M10 6.5h.01M15 7.5h.01M17 11.5h.01"/>'
    ,monitor: '<rect x="3" y="4" width="18" height="13" rx="2"/><path d="M8 21h8M12 17v4"/>'
    ,textSize: '<path d="M4 6V4h10v2M9 4v16M6 20h6M15 9V7h6v2M18 7v13M16 20h4"/>'
    ,comment: '<path d="M21 15a4 4 0 0 1-4 4H8l-5 3V7a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4Z"/>'
    ,eye: '<path d="M2 12s3.5-6 10-6 10 6 10 6-3.5 6-10 6S2 12 2 12Z"/><circle cx="12" cy="12" r="2.5"/>'
    ,keyboard: '<rect x="3" y="6" width="18" height="12" rx="2"/><path d="M7 10h.01M11 10h.01M15 10h.01M18 10h.01M7 14h.01M10 14h7"/>'
    ,clock: '<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'
    ,file: '<path d="M6 3h8l4 4v14H6z"/><path d="M14 3v5h5"/>'
    ,diff: '<circle cx="7" cy="5" r="2"/><circle cx="17" cy="19" r="2"/><path d="M7 7v12M17 5v12M13 9l4-4 4 4"/>'
    ,bell: '<path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/>'
    ,volume: '<path d="M5 10v4h4l5 4V6l-5 4H5Z"/><path d="M17 9a4 4 0 0 1 0 6M19 6a8 8 0 0 1 0 12"/>'
    ,eyeClosed: '<path d="m3 3 18 18M10.6 10.6a2 2 0 0 0 2.8 2.8M9.9 5.2A11 11 0 0 1 12 5c6.5 0 10 7 10 7a16 16 0 0 1-2.2 3.2M6.6 6.6C3.7 8.5 2 12 2 12s3.5 7 10 7a10 10 0 0 0 4.1-.9"/>'
    ,play: '<path d="m8 5 11 7-11 7Z"/>'
    ,folder: '<path d="M3 6h7l2 2h9v11H3z"/>'
    ,layers: '<path d="m12 3 9 5-9 5-9-5 9-5Z"/><path d="m3 12 9 5 9-5M3 16l9 5 9-5"/>'
    ,discard: '<path d="M4 7v5h5"/><path d="M6.1 17.6A8 8 0 1 0 4 12"/>'
    ,circle: '<circle cx="12" cy="12" r="5" fill="currentColor" stroke="none"/>'
  };
  const icon = name => `<svg viewBox="0 0 24 24" aria-hidden="true">${icons[name] || icons.code}</svg>`;
  const esc = value => String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const attr = value => esc(value).replace(/`/g, '&#96;');
  const post = (action, data = {}) => window.codexHost(JSON.stringify({action, ...data}));
  const labels = {
    approval: {'untrusted':'谨慎审批','on-request':'按需审批','never':'全自动'},
    effort: {'minimal':'最少','low':'低','medium':'中','high':'高','xhigh':'极高','ultra':'最高'},
    sandbox: {'read-only':'只读','workspace-write':'工作区','danger-full-access':'完全访问'},
    serviceTier: {'standard':'标准','fast':'Fast'}
  };
  let toastTimer = null;
  let questionTimer = null;

  function resolvedTheme(){return state.appearanceTheme==='system'?(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark'):state.appearanceTheme;}
  function writePreference(key,value){try{localStorage.setItem(`codex-gui.${key}`,String(value));}catch(_){} }
  function applyAppearance(){
    const theme=resolvedTheme(),rootStyle=document.documentElement.style,scale=Math.min(140,Math.max(80,Number(state.appearanceScale)||100))/100;
    document.documentElement.dataset.theme=theme;
    rootStyle.setProperty('--bg',state.chatBgColor||(theme==='light'?'#ffffff':'#1e1e1e'));
    rootStyle.setProperty('--bar',state.chatBarColor||(theme==='light'?'#f3f3f3':'#252526'));
    rootStyle.setProperty('--user',state.userMsgColor||(theme==='light'?'#0078d4':'#005fb8'));
    document.body.style.zoom=String(scale);
    document.body.style.width=`${100/scale}%`;
    document.body.style.height=`${100/scale}%`;
  }
  function updateAppearance(key,value,storageKey){state[key]=value;writePreference(storageKey,value);applyAppearance();render();}

  function markdown(text) {
    const blocks=[];
    let source=esc(text||'').replace(/```([^\n]*)\n([\s\S]*?)```/g,(_,lang,code)=>{const id=blocks.length;blocks.push(`<div class="code-block"><div class="code-lang">${lang||'text'}</div><button class="copy-code" data-copy="${attr(code)}" title="复制">${icon('copy')}</button><pre>${code}</pre></div>`);return `\n§§BLOCK${id}§§\n`;});
    source=source.replace(/^### (.+)$/gm,'<h3>$1</h3>').replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^# (.+)$/gm,'<h1>$1</h1>').replace(/`([^`]+)`/g,'<code>$1</code>').replace(/\*\*([^*]+)\*\*/g,'<strong>$1</strong>').replace(/\[([^\]]+)]\((https?:\/\/[^)]+)\)/g,'<a href="$2">$1</a>');
    return `<div class="markdown">${source.split(/\n{2,}/).map(part=>{const token=part.trim().match(/^§§BLOCK(\d+)§§$/);if(token)return blocks[Number(token[1])];if(/^(?:[-*] .+(?:\n|$))+/.test(part.trim()))return '<ul>'+part.trim().split('\n').map(line=>`<li>${line.replace(/^[-*] /,'')}</li>`).join('')+'</ul>';return part.trim()?`<p>${part.replace(/\n/g,'<br>')}</p>`:'';}).join('')}</div>`;
  }

  function header() {
    const secondary=state.view!=='chat', title=state.view==='history'?'历史会话':state.view==='settings'?'设置':state.title;
    return `<header class="header"><div class="header-left">${secondary?`<button class="icon-btn back" data-action="back">${icon('back')}<span>返回</span></button>`:''}<div class="session-wrap"><div class="session-title">${esc(title)}</div>${!secondary&&state.threadId?`<button class="icon-btn title-edit" data-action="rename" title="重命名">${icon('edit')}</button>`:''}</div></div><div class="header-right"><button class="icon-btn" data-action="new" title="新会话">${icon('plus')}</button>${!secondary?`<button class="icon-btn" data-action="conversationSearch" title="搜索">${icon('search')}</button>`:''}<button class="icon-btn" data-action="history" title="历史会话">${icon('history')}</button><button class="icon-btn" data-action="settings" title="设置">${icon('settings')}</button></div></header>`;
  }

  function messageView(entry,index) {
    const kind=entry.kind||'assistant';
    if(kind==='user')return `<article class="message user" data-message="${index}"><div class="message-meta">你</div><div class="message-body">${esc(entry.body)}</div></article>`;
    if(kind==='assistant')return `<article class="message assistant" data-message="${index}"><div class="message-body">${markdown(entry.body)}</div></article>`;
    if(kind==='notice')return `<article class="message notice" data-message="${index}">${esc(entry.title)}${entry.body?` · ${esc(entry.body)}`:''}</article>`;
    const names={reasoning:'推理',plan:'计划',command:'命令',mcp:'MCP 工具',error:'错误'};
    return `<article class="message tool ${kind}" data-message="${index}"><div class="tool-card"><div class="tool-head"><span class="tool-kind">${esc(names[kind]||entry.title||'Codex')}</span><span>${esc(entry.title&&entry.title!==names[kind]?entry.title:'')}</span></div><div class="tool-body">${esc(entry.body)}</div></div></article>`;
  }

  function messagesView() {
    if(!state.messages.length)return `<div class="messages" id="messages"><div class="welcome"><div class="welcome-mark">${icon('codex')}</div><h2>Codex</h2><p>Codex CLI 的原生 JetBrains 工作台。没有供应商切换，也不会注入第三方增强提示词。</p></div></div>`;
    const rail=state.messages.length>2;
    return `${rail?`<div class="anchor-rail"><div class="anchor-track"></div>${state.messages.map((m,i)=>`<button class="anchor-dot" style="top:${((i+.5)/state.messages.length)*100}%" data-anchor="${i}" title="${attr((m.body||m.title||'').slice(0,80))}"></button>`).join('')}</div>`:''}<div class="messages${rail?' has-rail':''}" id="messages">${state.messages.map(messageView).join('')}</div>`;
  }

  function changeStats(change){let plus=0,minus=0;(change.diff||'').split('\n').forEach(line=>{if(line.startsWith('+')&&!line.startsWith('+++'))plus++;if(line.startsWith('-')&&!line.startsWith('---'))minus++;});return{plus,minus};}
  function statusPanel(){if(!state.statusPanelExpanded)return'';const totals=state.changes.reduce((sum,c)=>{const x=changeStats(c);sum.plus+=x.plus;sum.minus+=x.minus;return sum;},{plus:0,minus:0});let pop='';if(state.statusOpen==='changes')pop=`<div class="status-popover"><div class="status-popover-head"><strong>待处理修改</strong><div class="status-actions"><button class="text-btn" data-action="acceptAll" ${state.changes.length?'':'disabled'}>全部接受</button><button class="text-btn danger" data-action="revertAll" ${state.changes.length?'':'disabled'}>全部撤销</button></div></div><div class="change-list">${state.changes.length?state.changes.map((c,i)=>{const s=changeStats(c),kind=(c.kind||'modified').toLowerCase(),mark=kind==='added'?'A':kind==='deleted'?'D':'M';return `<div class="change-row"><span class="change-kind ${kind}">${mark}</span><span class="change-name" data-open-change="${i}" title="${attr(c.path)}">${esc(c.path)}</span><span class="change-stats"><b class="plus">+${s.plus}</b><b class="minus">-${s.minus}</b></span><span class="change-buttons"><button class="mini-btn" data-accept="${i}" title="接受">✓</button><button class="mini-btn" data-revert="${i}" title="撤销">↶</button></span></div>`;}).join(''):'<div class="empty-panel">当前没有待处理文件修改</div>'}</div></div>`;if(state.statusOpen==='tasks')pop='<div class="status-popover"><div class="status-popover-head"><strong>Codex 任务</strong></div><div class="empty-panel">计划与工具执行状态会显示在消息时间线中</div></div>';return `<div class="status-panel">${pop}<div class="status-tabs"><button class="status-tab${state.statusOpen==='tasks'?' active':''}" data-status="tasks">${icon('branch')}<span>任务</span></button><button class="status-tab${state.statusOpen==='changes'?' active':''}" data-status="changes">${icon('code')}<span>修改 ${state.changes.length}</span><span class="change-stats"><b class="plus">+${totals.plus}</b><b class="minus">-${totals.minus}</b></span></button></div></div>`;}

  function selector(name,value,items,iconName,title){const open=state.openMenu===name;return `<div class="selector-shell"><button class="selector-button ${name==='approval'&&value==='never'?'automatic':''}" data-menu="${name}" title="${attr(title)}">${icon(iconName)}<span class="selector-button-text">${esc((labels[name]||{})[value]||value||'默认')}</span>${icon('down')}</button>${open?`<div class="selector-menu">${items.map(item=>`<button class="selector-option${item===value?' selected':''}" data-choice="${name}" data-value="${attr(item)}"><span>${esc((labels[name]||{})[item]||item||'默认')}</span>${item===value?icon('check'):''}</button>`).join('')}</div>`:''}</div>`;}
  function approvalSelector(){const choices=[['untrusted','chat','谨慎模式','最安全的选择，每一步都需要你亲自批准。'],['on-request','robot','自动编辑','保持正常编辑流程，仅在需要时进行审批。'],['never','bolt','全自动','文件和执行命令立即生效，仅受沙箱限制。']];const open=state.openMenu==='approval';return `<div class="selector-shell approval-shell"><button class="selector-button ${state.approval==='never'?'automatic':''}" data-menu="approval" title="审批模式">${icon('bolt')}<span class="selector-button-text">${esc(labels.approval[state.approval]||'按需审批')}</span>${icon('down')}</button>${open?`<div class="selector-menu approval-menu">${choices.map(([value,ico,title,description])=>`<button class="approval-option${state.approval===value?' selected':''}" data-choice="approval" data-value="${value}"><span class="approval-icon">${icon(ico)}</span><span class="approval-copy"><b>${title}</b><small>${description}</small></span>${state.approval===value?icon('check'):''}</button>`).join('')}</div>`:''}</div>`;}
  function toggleRow(iconName,title,description,on,action){return `<button class="config-row" data-action="${action}"><span class="config-icon">${icon(iconName)}</span><span class="config-copy"><b>${title}</b>${description?`<small>${description}</small>`:''}</span><span class="switch ${on?'on':''}" aria-hidden="true"></span></button>`;}
  function composerSubmenu(){if(state.composerSubmenu==='agents'){const items=`<button class="submenu-option${state.activeAgentId?'':' selected'}" data-agent-select=""><span class="config-icon">${icon('codex')}</span><span class="config-copy"><b>默认身份</b><small>不添加 Agent 身份指令</small></span>${state.activeAgentId?'':icon('check')}</button>`+state.agents.map(agent=>`<button class="submenu-option${state.activeAgentId===agent.id?' selected':''}" data-agent-select="${attr(agent.id)}"><span class="config-icon">${icon('robot')}</span><span class="config-copy"><b>${esc(agent.name)}</b><small>${esc(agent.instructions)}</small></span>${state.activeAgentId===agent.id?icon('check'):''}</button>`).join('');return `<div class="composer-submenu"><div class="submenu-list">${items}</div><button class="submenu-create" data-settings-go="agents">${icon('plus')}<span><b>管理提示词</b><small>前往设置进行新建和编辑</small></span></button></div>`;}if(state.composerSubmenu==='process')return `<div class="composer-submenu process-submenu"><div class="process-status"><span class="process-dot ${state.connected?'online':''}"></span><span><b>${state.connected?'Codex CLI 已连接':'Codex CLI 未连接'}</b><small>${state.connected?'1 个本地 app-server 进程':'可尝试重新启动本地进程'}</small></span></div><button class="submenu-create" data-action="reconnect">${icon('server')}<span><b>重新连接</b><small>重启 Codex CLI 进程</small></span></button></div>`;return'';}
  function composerMenu(){if(!state.composerMenu)return'';const agent=state.agents.find(item=>item.id===state.activeAgentId);return `<div class="composer-menu-shell"><div class="composer-menu"><button class="config-row${state.composerSubmenu==='agents'?' active':''}" data-composer-submenu="agents"><span class="config-icon">${icon('note')}</span><span class="config-copy"><b>提示词</b><small>${esc(agent?.name||'未启用')}</small></span>${icon('chevron')}</button><div class="menu-divider"></div><button class="config-row${state.composerSubmenu==='process'?' active':''}" data-composer-submenu="process"><span class="config-icon">${icon('server')}</span><span class="config-copy"><b>Codex CLI 进程</b><small>${state.connected?'1 个进程 · 已连接':'未连接'}</small></span>${icon('chevron')}</button><div class="menu-divider"></div>${toggleRow('code','流式传输','',state.streamResponses,'toggleStreaming')}${toggleRow('bulb','思考过程','',state.showReasoning,'toggleReasoning')}</div>${composerSubmenu()}</div>`;}
  function formatTokens(value){const n=Number(value)||0;if(n>=1000){const k=n/1000;return `${Number.isInteger(k)?k:k.toFixed(1)}k`;}return String(n);}
  function tokenIndicator(){const percentage=Math.max(0,Math.min(100,Number(state.usagePercentage)||0)),size=14,radius=(size-3)/2,circumference=2*Math.PI*radius,offset=circumference*(1-percentage/100),detail=state.usageMaxTokens?`${percentage.toFixed(1)}% · ${formatTokens(state.usageUsedTokens)} / ${formatTokens(state.usageMaxTokens)} 上下文`:`上下文已使用 ${percentage.toFixed(1)}%`;return `<span class="token-indicator"><span class="token-ring-wrap"><svg class="token-ring" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}"><circle class="token-ring-bg" cx="${size/2}" cy="${size/2}" r="${radius}"/><circle class="token-ring-fill" cx="${size/2}" cy="${size/2}" r="${radius}" stroke-dasharray="${circumference}" stroke-dashoffset="${offset}"/></svg><span class="token-tooltip">${esc(detail)}</span></span><span>${Math.round(percentage)}%</span></span>`;}
  function attachmentList(){if(!state.attachments.length)return'';return `<div class="attachment-list">${state.attachments.map((a,i)=>`<div class="attachment-item" title="${attr(a.path||a.name)}"><span class="attachment-kind">${icon(a.kind==='IMAGE'?'image':'file')}</span><span class="attachment-name">${esc(a.name)}</span><button class="attachment-remove" data-remove-attachment="${i}" title="移除附件">×</button></div>`).join('')}</div>`;}
  function contextBar(){const activeFile=String(state.activeFile||''),fileName=activeFile.split(/[/\\]/).pop()||activeFile;let context='';if(activeFile)context=`<span class="context-item" title="${attr(activeFile)}">${icon('file')}<span class="context-text">${esc(fileName)}</span><button data-action="clearFileContext" title="移除文件上下文">×</button></span>`;else if(!state.sendOpenedFilePath)context=`<span class="file-context-shell"><button class="file-context-placeholder" data-action="showFileContextPrompt" title="文件上下文">${icon('file')}<span>文件上下文</span></button>${state.fileContextPrompt?`<span class="file-context-popover"><b>开启文件上下文？</b><span>开启后，发送消息时会自动附带当前编辑器文件路径。</span><span class="file-context-actions"><button data-action="cancelFileContext">取消</button><button class="primary" data-action="enableFileContext">开启</button></span></span>`:''}</span>`;return `<div class="context-row"><span class="context-tools"><button class="context-tool-btn" data-action="pickFile" title="添加附件">${icon('paperclip')}</button>${tokenIndicator()}<i class="context-divider"></i></span>${context}<span class="context-tools-right"><button class="context-tool-btn" data-action="toggleStatusPanel" title="${state.statusPanelExpanded?'隐藏状态面板':'显示状态面板'}">${icon(state.statusPanelExpanded?'down':'layers')}</button><button class="context-tool-btn" data-action="rewind" title="回溯" ${!state.threadId||state.busy?'disabled':''}>${icon('discard')}</button></span></div>`;}
  function composer(){const modelItems=state.models.length?state.models:[''],shortcutHint=state.sendShortcut==='cmdEnter'?'Ctrl+Enter 发送':'Enter 发送';return `<div class="input-area"><div class="composer"><span class="composer-grip" aria-hidden="true"></span>${attachmentList()}${contextBar()}<div class="input-wrap"><textarea id="prompt" class="input" placeholder="@引用文件，#唤起智能体，;插入提示词，${shortcutHint}"></textarea></div><div class="toolbar"><div class="toolbar-left"><span class="toolbar-settings">${composerMenu()}<button class="toolbar-icon" data-action="composerSettings" title="聊天设置">${icon('sliders')}</button></span><button class="toolbar-icon provider-mark" title="Codex">${icon('codex')}</button>${approvalSelector()}${selector('model',state.model,modelItems,'codex','模型')}${selector('effort',state.effort,['minimal','low','medium','high','xhigh','ultra'],'bulb','推理强度')}${selector('serviceTier',state.serviceTier,['standard','fast'],state.serviceTier==='fast'?'bolt':'circle','响应模式')}</div><div class="toolbar-right"><button class="toolbar-icon" data-action="composerSettings" title="提示词">${icon('spark')}</button>${state.busy?`<button class="submit stop" data-action="stop" title="停止">${icon('stop')}</button>`:`<button class="submit" data-action="send" title="发送">${icon('send')}</button>`}</div></div></div></div>`;}
  function chatPage(){return `<main class="chat-page"><div class="messages-shell">${messagesView()}</div>${statusPanel()}${composer()}</main>`;}
  function historyPage(){return `<main class="page"><div class="page-toolbar"><input id="historySearch" class="search" value="${attr(state.historySearch)}" placeholder="搜索历史会话"><button class="text-btn" data-action="export">导出当前会话</button></div><div class="history-list">${state.history.length?state.history.map(h=>`<div class="history-item" data-thread="${attr(h.id)}"><div class="history-main"><span class="history-title">${h.favorite?'<span class="favorite">★</span>':''}${esc(h.title)}</span><span class="history-time">${esc(h.time||'')}</span></div><div class="history-meta">Codex CLI 会话 · ${esc(h.id.slice(0,12))}</div></div>`).join(''):'<div class="empty-panel">没有匹配的历史会话</div>'}</div></main>`;}

  const settingsTabs=[['basic','settings','基础设置'],['agents','robot','提示词'],['instructions','note','提示词库'],['skills','spark','Skills'],['mcp','server','MCP']];
  function appearanceColorField(key,storageKey,iconName,label,hint,presets,defaultValue){
    const current=state[key]||defaultValue;
    return `<div class="basic-field color-field"><div class="basic-field-header">${icon(iconName)}<span>${label}</span></div><div class="appearance-swatches">${presets.map(color=>`<button class="appearance-swatch ${current.toLowerCase()===color.toLowerCase()?'active':''}" style="--swatch:${color}" data-appearance-color="${key}" data-storage-key="${storageKey}" data-value="${color}" title="${color}" aria-label="${label} ${color}"><span></span></button>`).join('')}</div><div class="custom-color-row"><span>自定义颜色</span><label class="color-picker" style="--swatch:${current}"><input type="color" value="${attr(current)}" data-color-picker="${key}" data-storage-key="${storageKey}" aria-label="选择${label}"><i></i></label><input class="hex-color-input" value="${attr(current)}" data-color-text="${key}" data-storage-key="${storageKey}" aria-label="${label}十六进制值" spellcheck="false"><button class="appearance-reset" data-appearance-color="${key}" data-storage-key="${storageKey}" data-value="" title="恢复默认">${icon('refresh')}<span>恢复默认</span></button></div><small class="basic-hint">${icon('question')}<span>${hint}</span></small></div>`;
  }
  function appearanceSettings(){
    const light=resolvedTheme()==='light';
    const backgroundPresets=light?['#ffffff','#fafafa','#f5f5f5','#faf4ed','#f6f8fa','#fffbf0','#f0f4f8','#f5f0eb']:['#1e1e1e','#1a1b26','#282c34','#2b2d30','#0d1117','#1e1f29','#262335','#292d3e'];
    const barPresets=light?['#f3f3f3','#e5f0fb','#e5f2e9','#eee8f7','#f6ebe3','#f7e8ee','#e4f1f3','#e8e8e8']:['#252526','#1e3a5f','#263f36','#3b3151','#4a3428','#3f2b36','#243b4a','#3b3b3b'];
    const messagePresets=light?['#0078d4','#1a7f37','#8250df','#bf8700','#cf222e','#0e8a9a','#7c5cbf','#57606a']:['#005fb8','#1a7f37','#6e40c9','#9a6700','#cf222e','#0e6b8a','#6b4c9a','#4a5568'];
    return `<div class="basic-tab-content"><div class="basic-field theme-field"><div class="basic-field-header">${icon('palette')}<span>界面主题</span></div><div class="theme-options">${[['system','monitor','跟随 IDE'],['light','palette','亮色'],['dark','bulb','暗色']].map(([value,ico,label])=>`<button class="theme-option ${state.appearanceTheme===value?'active':''}" data-appearance-theme="${value}"><span class="theme-option-icon ${value}">${icon(ico)}</span><b>${label}</b></button>`).join('')}</div></div><div class="basic-field"><div class="basic-field-header">${icon('textSize')}<label for="appearanceScale">字体大小</label></div><select id="appearanceScale" class="appearance-select">${[[80,'小（80%）'],[90,'较小（90%）'],[100,'标准（100%）'],[110,'较大（110%）'],[120,'大（120%）'],[140,'最大（140%）']].map(([value,label])=>`<option value="${value}" ${Number(state.appearanceScale)===value?'selected':''}>${label}</option>`).join('')}</select></div>${appearanceColorField('chatBgColor','chat-bg','palette','聊天背景色','修改会话与设置内容区的背景颜色。',backgroundPresets,light?'#ffffff':'#1e1e1e')}${appearanceColorField('chatBarColor','chat-bar','monitor','聊天栏颜色','顶部栏、状态栏与设置侧栏共用此颜色。',barPresets,light?'#f3f3f3':'#252526')}${appearanceColorField('userMsgColor','user-message','comment','用户消息颜色','修改聊天中用户消息气泡的强调颜色。',messagePresets,light?'#0078d4':'#005fb8')}</div>`;
  }
  function behaviorField(iconName,label,hint,control,className=''){return `<div class="basic-field behavior-field ${className}"><div class="basic-field-header">${icon(iconName)}<span>${label}</span></div>${control}${hint?`<small class="basic-hint">${icon('question')}<span>${hint}</span></small>`:''}</div>`;}
  function behaviorToggle(key,on){return `<button class="behavior-toggle" data-behavior-toggle="${key}" aria-pressed="${on}"><span class="behavior-switch ${on?'on':''}"></span><span>${on?'已开启':'已关闭'}</span></button>`;}
  function shortcutSettings(){return `<div class="basic-field behavior-field"><div class="basic-field-header">${icon('keyboard')}<span>发送快捷键</span></div><div class="shortcut-grid">${[['enter','Enter 发送','按 Enter 发送消息，Shift+Enter 换行'],['cmdEnter','⌘/Ctrl+Enter 发送','按 ⌘/Ctrl+Enter 发送消息，Enter 换行']].map(([value,title,description])=>`<button class="shortcut-card ${state.sendShortcut===value?'active':''}" data-send-shortcut="${value}">${state.sendShortcut===value?`<span class="shortcut-check">${icon('check')}</span>`:''}<b>${title}</b><small>${description}</small></button>`).join('')}</div></div>`;}
  function soundSelector(){const options=[['default','默认'],['chime','清脆铃声'],['bell','钟声'],['ding','叮咚'],['success','成功提示'],['custom','自定义...']],selected=options.find(item=>item[0]===state.notificationSound)||options[0];return `<div class="sound-select-row"><div class="sound-select"><button class="sound-select-trigger ${state.soundMenuOpen?'open':''}" data-sound-menu>${esc(selected[1])}${icon('down')}</button>${state.soundMenuOpen?`<div class="sound-select-menu">${options.map(([value,label])=>`<button class="sound-select-option ${state.notificationSound===value?'selected':''}" data-sound-option="${value}"><span>${label}</span>${state.notificationSound===value?icon('check'):''}</button>`).join('')}</div>`:''}</div><button class="sound-test-btn" data-action="testNotificationSound" title="试听">${icon('play')}</button></div>`;}
  function behaviorSettings(){
    const hasSystemNotification=state.askUserQuestionNotificationEnabled||state.taskCompletionNotificationEnabled;
    const hasSoundNotification=state.askUserQuestionSoundEnabled||state.taskCompletionSoundEnabled;
    const notificationDetails=hasSystemNotification||hasSoundNotification?`<div class="notification-details">${hasSystemNotification?behaviorField('eyeClosed','仅在 IDE 未聚焦时显示系统通知','开启后，仅在 IDE 窗口未聚焦时显示任务完成和提问系统通知。',behaviorToggle('systemNotificationOnlyWhenUnfocused',state.systemNotificationOnlyWhenUnfocused),'notification-detail-field'):''}${hasSoundNotification?`${behaviorField('eyeClosed','仅在 IDE 未聚焦时播放提示音','开启后，仅在 IDE 窗口未聚焦时播放任务完成和提问提示音。',behaviorToggle('soundOnlyWhenUnfocused',state.soundOnlyWhenUnfocused),'notification-detail-field')}${behaviorField('volume','提示音','',soundSelector(),'notification-detail-field')}${state.notificationSound==='custom'?behaviorField('file','自定义音频文件','支持 WAV、MP3、AIFF 格式。',`<div class="custom-sound-row"><input id="customSoundPath" class="custom-sound-input" value="${attr(state.customSoundPath)}" placeholder="选择或输入音频文件路径"><button class="basic-action-btn" data-action="browseNotificationSound">${icon('folder')}<span>浏览</span></button><button class="basic-action-btn" data-action="saveCustomSound">保存</button></div>`,'notification-detail-field'):''}`:''}</div>`:'';
    return `<div class="basic-tab-content behavior-content">${shortcutSettings()}${behaviorField('clock','权限与提问对话框超时时间','设置提问对话框和权限请求对话框的超时时间（30~3600 秒）。超时后对话框将自动关闭，Codex 会继续执行。',`<div class="timeout-row"><input id="permissionDialogTimeout" type="number" min="30" max="3600" value="${attr(state.permissionDialogTimeoutSeconds)}"><span>秒</span></div>`)}${behaviorField('refresh','流式传输','开启后，AI 回复将实时逐字显示，而非等待完整响应后一次性展示。可能会消耗更多资源。',behaviorToggle('streamResponses',state.streamResponses))}${behaviorField('file','发送打开的文件路径','开启后，发送消息时会自动将当前编辑器文件路径告诉 AI（只传递文件路径，不传文件内容）。',behaviorToggle('sendOpenedFilePath',state.sendOpenedFilePath))}${behaviorField('diff','默认展开差异','开启后，收到文件修改时将默认展开差异面板。',behaviorToggle('diffExpandedByDefault',state.diffExpandedByDefault))}${behaviorField('comment','新建会话时二次确认','关闭后，在已有消息的会话中点击新建将直接创建，不再弹出确认窗口。',behaviorToggle('newSessionConfirmEnabled',state.newSessionConfirmEnabled))}${behaviorField('bell','提问系统通知','开启后，当 Codex 向你提问时显示系统通知提醒，避免错过。',behaviorToggle('askUserQuestionNotificationEnabled',state.askUserQuestionNotificationEnabled))}${behaviorField('volume','提问提示音','开启后，当 Codex 向你提问时播放已配置的提示音。会使用下方的音效选择和焦点规则。',behaviorToggle('askUserQuestionSoundEnabled',state.askUserQuestionSoundEnabled))}${behaviorField('bell','任务完成系统通知','开启后，当 AI 任务完成时显示系统通知。',behaviorToggle('taskCompletionNotificationEnabled',state.taskCompletionNotificationEnabled))}${behaviorField('volume','任务完成提示音','开启后，AI 完成任务时会播放提示音，方便您离开屏幕时也能知道任务已完成。',behaviorToggle('taskCompletionSoundEnabled',state.taskCompletionSoundEnabled))}${notificationDetails}</div>`;
  }
  function basicSettings(){const content=state.basicSettingsTab==='behavior'?behaviorSettings():appearanceSettings();return `<section class="settings-content-section basic-config-section"><div class="section-heading basic-heading"><h2>基础配置</h2><p>配置页面外观和 Codex 会话行为</p></div><div class="basic-tab-selector"><button class="basic-tab-btn ${state.basicSettingsTab==='appearance'?'active':''}" data-basic-tab="appearance">${icon('palette')}<span>外观</span></button><button class="basic-tab-btn ${state.basicSettingsTab==='behavior'?'active':''}" data-basic-tab="behavior">${icon('settings')}<span>行为</span></button></div>${content}</section>`;}
  function instructionsSettings(){return `<section class="settings-content-section"><div class="section-heading"><h2>提示词库</h2><p>全局提示词适用于所有项目，项目提示词仅作用于当前工作区；两者会作为 Codex 原生 developer instructions 传入新会话。</p></div><div class="editor-card"><label>全局提示词<span>适用于所有项目</span></label><textarea id="globalInstructions" class="large-input" placeholder="例如：始终使用中文回复">${esc(state.globalInstructions)}</textarea></div><div class="editor-card"><label>项目提示词<span>仅保存到当前项目的工作区配置</span></label><textarea id="projectInstructions" class="large-input" placeholder="例如：遵循本项目的目录和测试约定">${esc(state.projectInstructions)}</textarea></div><div class="settings-actions"><button class="primary-btn" data-action="saveInstructions">保存提示词</button></div></section>`;}
  function agentsSettings(){return `<section class="settings-content-section"><div class="section-heading action-heading"><div><h2>Agent 身份</h2><p>选择一个身份后，它的指令会用于之后创建的新会话。</p></div><button class="primary-btn" data-action="newAgent">＋ 新建 Agent</button></div><div class="agent-list"><button class="agent-card ${!state.activeAgentId?'active':''}" data-agent-select=""><span class="agent-avatar">${icon('codex')}</span><span class="agent-info"><b>默认 Codex</b><small>不添加 Agent 身份指令</small></span>${!state.activeAgentId?icon('check'):''}</button>${state.agents.map(agent=>`<div class="agent-card ${state.activeAgentId===agent.id?'active':''}"><button class="agent-main" data-agent-select="${attr(agent.id)}"><span class="agent-avatar">${icon('robot')}</span><span class="agent-info"><b>${esc(agent.name)}</b><small>${esc(agent.instructions.slice(0,90))}${agent.instructions.length>90?'…':''}</small></span>${state.activeAgentId===agent.id?icon('check'):''}</button><button class="card-action" data-agent-edit="${attr(agent.id)}" title="编辑">${icon('edit')}</button><button class="card-action danger" data-agent-delete="${attr(agent.id)}" title="删除">${icon('trash')}</button></div>`).join('')}</div></section>`;}
  const scopeLabels={user:'用户',repo:'项目',system:'系统',admin:'管理员'};
  const authLabels={oAuth:'OAuth 已登录',bearerToken:'令牌认证',notLoggedIn:'需要登录',unsupported:'无需认证',unknown:'认证未知'};
  function safeColor(value){return /^#[0-9a-f]{3,8}$/i.test(value||'')?value:'';}
  function mcpTools(server){return Array.isArray(server.tools)?server.tools:Object.entries(server.tools||{}).map(([name,tool])=>({name,...(tool||{})}));}
  function mcpStatus(server){
    if(server.enabled===false)return{kind:'disabled',text:'已禁用'};
    if(server.authStatus==='notLoggedIn')return{kind:'warning',text:'需要认证'};
    if(server.connectionStatus==='connected')return{kind:'connected',text:'连接成功'};
    return{kind:'failed',text:'连接失败'};
  }
  function mcpCommand(config){
    if(config.command)return [config.command,...(Array.isArray(config.args)?config.args:[])].join(' ');
    return config.url||'';
  }
  function mcpColor(name){const colors=['#8854e8','#3979d2','#d05a72','#278f78','#b66a2c','#6873d9'];let hash=0;for(const char of name||'M')hash=(hash*31+char.charCodeAt(0))>>>0;return colors[hash%colors.length];}
  function redactMcpSecrets(value,key=''){
    if(/token|secret|password|authorization|api[_-]?key/i.test(key))return '***';
    if(Array.isArray(value))return value.map(item=>redactMcpSecrets(item));
    if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([childKey,child])=>[childKey,redactMcpSecrets(child,childKey)]));
    return value;
  }
  function mcpCopyText(server){return JSON.stringify({mcpServers:{[server.name]:redactMcpSecrets(server.config||{})}},null,2);}
  function addMcpActivity(message,level='info',serverName=''){
    state.mcpActivity.push({time:new Date().toLocaleTimeString('zh-CN',{hour12:false}),message,level,serverName});
    state.mcpActivity=state.mcpActivity.slice(-100);
  }
  // Codex 一次返回服务器状态和工具列表，这里按 CC-Gui 的阶段粒度展开为可检查日志。
  function logMcpSnapshot(servers){
    const items=Array.isArray(servers)?servers:[],counts={connected:0,failed:0,warning:0,disabled:0};
    for(const server of items){
      const status=mcpStatus(server),tools=mcpTools(server),name=server.serverInfo?.title||server.name||'';
      counts[status.kind]=(counts[status.kind]||0)+1;
      if(server.enabled===false)addMcpActivity('服务器已停用','info',name);
      else if(status.kind==='failed')addMcpActivity('连接失败，未获取到可用工具','error',name);
      else if(status.kind==='warning')addMcpActivity('需要认证或正在连接，暂无可用工具','warning',name);
      else if(tools.length)addMcpActivity(`工具加载完成，共 ${tools.length} 个`,'success',name);
      else addMcpActivity('服务器已连接，但没有可用工具','warning',name);
    }
    addMcpActivity(`服务器状态更新完成：共 ${items.length} 个，已连接 ${counts.connected||0}，失败 ${counts.failed||0}，待处理 ${counts.warning||0}，已停用 ${counts.disabled||0}`,counts.failed?'warning':'success');
  }
  function mcpToolsPanel(server){
    const tools=mcpTools(server),status=mcpStatus(server);
    return `<div class="mcp-tools-panel"><div class="mcp-tools-head"><b>工具</b><button class="mcp-tool-refresh" data-action="reloadMcp" data-mcp-server="${attr(server.name)}" title="刷新工具列表">${icon('refresh')}</button></div><div class="mcp-tools-body">${tools.length?`<div class="mcp-tool-count">工具 (${tools.length})</div><div class="mcp-tool-list">${tools.map(tool=>`<div class="mcp-tool-row" title="${attr(tool.description||tool.name)}">${icon('code')}<span>${esc(tool.name)}</span></div>`).join('')}</div>`:`<div class="mcp-no-tools ${status.kind==='failed'?'failed':''}">${status.kind==='failed'?'服务器未连接':'无工具'}</div>`}</div></div>`;
  }
  function mcpServerCard(server){
    const expanded=state.expandedMcpName===server.name,status=mcpStatus(server),config=server.config||{},info=server.serverInfo||{},managed=server.managed===true,command=mcpCommand(config);
    return `<article class="mcp-server-card ${expanded?'expanded':''} ${server.enabled===false?'disabled':''}"><div class="mcp-card-header" data-mcp-expand="${attr(server.name)}"><div class="mcp-card-main"><span class="mcp-expand">${icon('down')}</span><span class="mcp-avatar" style="--mcp-color:${mcpColor(server.name)}">${esc((info.title||server.name||'M').slice(0,1).toUpperCase())}</span><b class="mcp-name">${esc(info.title||server.name)}</b><span class="mcp-status-icon ${status.kind}" title="${attr(status.text)}">${icon(status.kind==='connected'?'check':status.kind==='warning'?'alert':'close')}</span></div><div class="mcp-card-actions"><button class="mcp-icon-btn" data-mcp-edit="${attr(server.name)}" title="编辑配置" ${managed?'disabled':''}>${icon('edit')}</button><button class="mcp-icon-btn" data-mcp-copy="${attr(server.name)}" title="复制配置">${icon('copy')}</button><button class="mcp-icon-btn danger" data-mcp-delete="${attr(server.name)}" title="删除服务器" ${managed?'disabled':''}>${icon('trash')}</button><button class="mcp-toggle ${server.enabled===false?'':'on'}" data-mcp-toggle="${attr(server.name)}" title="${server.enabled===false?'启用服务器':'停用服务器'}" aria-label="${server.enabled===false?'启用服务器':'停用服务器'}" ${managed?'disabled':''}><span></span></button></div></div>${expanded?`<div class="mcp-card-content"><div class="mcp-info-section"><div class="mcp-info-row"><span>连接状态:</span><b class="mcp-status-value ${status.kind}">${icon(status.kind==='connected'?'check':status.kind==='warning'?'alert':'close')}${esc(status.text)}</b></div>${info.version?`<div class="mcp-info-row"><span>服务器版本:</span><b>${esc(info.name||server.name)} v${esc(info.version)}</b></div>`:''}${command?`<div class="mcp-info-row"><span>${config.command?'命令':'URL'}:</span><code>${esc(command)}</code></div>`:''}${server.authStatus==='notLoggedIn'?`<div class="mcp-login-row"><button class="primary-btn" data-mcp-login="${attr(server.name)}">登录服务器</button></div>`:''}</div>${mcpToolsPanel(server)}</div>`:''}</article>`;
  }
  function mcpSettings(){
    const cards=state.mcpServers.map(mcpServerCard).join('');
    return `<section class="settings-content-section mcp-settings"><div class="section-heading mcp-page-heading"><div class="mcp-page-title"><h2>MCP 服务器</h2><button class="mcp-help-btn" data-action="mcpHelp" title="什么是 MCP">${icon('question')}</button></div><p>配置和管理 Model Context Protocol 服务器</p></div><div class="mcp-section-head"><div class="mcp-head-actions"><button class="mcp-head-btn mcp-log-btn" data-action="mcpLogs" title="刷新日志">${icon('note')}${state.mcpActivity.length?`<span>${state.mcpActivity.length}</span>`:''}</button><button class="mcp-head-btn" data-action="reloadMcp" title="同步服务器状态">${icon('refresh')}</button><div class="mcp-add-shell"><button class="mcp-add-btn" data-action="mcpAddMenu">${icon('plus')}<span>添加</span>${icon('down')}</button>${state.mcpAddOpen?`<div class="mcp-add-menu"><button data-action="newMcp">${icon('code')}<span>手动配置</span></button><button data-action="openMcpConfig">${icon('edit')}<span>编辑 config.toml</span></button></div>`:''}</div></div></div><div class="mcp-server-list">${cards||`<div class="mcp-empty"><span>${icon('server')}</span><b>没有已配置的 MCP 服务器</b><small>添加服务器后，Codex 会自动连接并读取工具。</small><button class="primary-btn" data-action="newMcp">${icon('plus')}添加服务器</button></div>`}</div></section>`;
  }
  function skillsSettings(){
    const query=state.skillSearch.trim().toLowerCase();
    const skills=state.skills.filter(skill=>(!query||`${skill.name} ${skill.description} ${skill.path} ${skill.interface?.displayName||''}`.toLowerCase().includes(query))&&(state.skillScope==='all'||skill.scope===state.skillScope)&&(state.skillStatus==='all'||(state.skillStatus==='enabled')===skill.enabled));
    const cards=skills.map(skill=>{
      const meta=skill.interface||{},expanded=state.selectedSkillPath===skill.path,color=safeColor(meta.brandColor);
      const detail=expanded?`<div class="skill-card-detail"><div class="skill-description"><span>描述</span><p>${esc(skill.description||meta.shortDescription||'此 Skill 没有提供说明。')}</p></div><div class="skill-card-actions"><button class="skill-action" data-open-skill="${attr(skill.path)}">${icon('external')}<span>打开源文件</span></button></div></div>`:'';
      return `<article class="skill-accordion ${expanded?'expanded':''} ${skill.enabled===false?'disabled':''}"><div class="skill-card-header"><button class="skill-check ${skill.enabled===false?'':'checked'}" data-skill-toggle="${attr(skill.path)}" data-skill-name="${attr(skill.name)}" title="${skill.enabled===false?'启用 Skill':'停用 Skill'}" aria-label="${skill.enabled===false?'启用 Skill':'停用 Skill'}">${skill.enabled===false?'':icon('check')}</button><span class="skill-card-icon skill-brand"${color?` style="--skill-color:${attr(color)}"`:''}>${icon('spark')}</span><button class="skill-card-main" data-skill-select="${attr(skill.path)}"><span><b>${esc(meta.displayName||skill.name)}</b><span class="scope-badge">${esc(scopeLabels[skill.scope]||skill.scope||'项目')}</span></span><code title="${attr(skill.path)}">${esc(skill.path)}</code></button><button class="skill-expand ${expanded?'expanded':''}" data-skill-select="${attr(skill.path)}" title="${expanded?'收起详情':'展开详情'}">${icon('down')}</button></div>${detail}</article>`;
    }).join('');
    const enabled=state.skills.filter(skill=>skill.enabled!==false).length,disabled=state.skills.length-enabled;
    const importMenu=state.skillImportOpen?`<div class="skill-import-menu"><button data-skill-import="user">${icon('codex')}<span><b>导入用户 Skill</b><small>复制到 ~/.codex/skills</small></span></button><button data-skill-import="repo">${icon('robot')}<span><b>导入项目 Skill</b><small>复制到当前项目 .codex/skills</small></span></button></div>`:'';
    return `<section class="settings-content-section integration-settings"><div class="section-heading action-heading"><div><h2>Skills</h2><p>勾选的 Skills 会由 Codex 自动发现并按需调用。</p></div><button class="card-action" data-action="reloadSkills" title="强制重新扫描 Skills">${icon('refresh')}</button></div><div class="integration-summary"><span><b>${state.skills.length}</b> 个 Skill</span><span><b>${enabled}</b> 个已启用</span><span><b>${disabled}</b> 个已停用</span></div>${state.skillErrors.length?`<div class="integration-warning"><b>${state.skillErrors.length} 个 Skill 无法加载</b>${state.skillErrors.slice(0,3).map(error=>`<span title="${attr(error.path||'')}">${esc(error.message||'未知解析错误')}</span>`).join('')}</div>`:''}<div class="integration-toolbar"><span class="search-shell">${icon('search')}<input id="skillSearch" value="${attr(state.skillSearch)}" placeholder="搜索名称、说明或路径"></span><div class="filter-group">${[['all','全部'],['user','用户'],['repo','项目'],['system','系统']].map(([key,label])=>`<button class="filter-button ${state.skillScope===key?'active':''}" data-skill-scope="${key}">${label}</button>`).join('')}</div><div class="filter-group">${[['all','全部状态'],['enabled','已启用'],['disabled','已停用']].map(([key,label])=>`<button class="filter-button ${state.skillStatus===key?'active':''}" data-skill-status="${key}">${label}</button>`).join('')}</div><div class="skill-import-shell"><button class="skill-add-button ${state.skillImportOpen?'active':''}" data-action="toggleSkillImport" title="导入 Skill">${icon('plus')}</button>${importMenu}</div></div>${state.skills.length?`<div class="skill-accordion-list">${cards||'<div class="list-empty">没有匹配的 Skill</div>'}</div>`:`<div class="settings-empty"><span>${icon('spark')}</span><b>当前工作区没有可用的 Skill</b><small>Codex 会从用户、项目与系统 Skills 目录中自动发现。</small><button class="primary-btn" data-action="toggleSkillImport">导入 Skill</button></div>`}</section>`;
  }
  function settingsPage(){const content=state.settingsTab==='instructions'?instructionsSettings():state.settingsTab==='agents'?agentsSettings():state.settingsTab==='skills'?skillsSettings():state.settingsTab==='mcp'?mcpSettings():basicSettings();return `<main class="settings-page ${state.settingsTab==='mcp'?'mcp-settings-page':''}"><aside class="settings-sidebar">${settingsTabs.map(([key,ico,label])=>`<button class="settings-nav ${state.settingsTab===key?'active':''}" data-settings-tab="${key}" aria-label="${attr(label)}" title="${attr(label)}">${icon(ico)}<span>${label}</span></button>`).join('')}</aside><div class="settings-content">${content}</div></main>`;}

  function agentDialog(){if(!state.agentEditor)return'';const agent=state.agentEditor;return `<div class="modal-overlay"><div class="modal-card agent-dialog"><div class="modal-heading"><div><h3>${agent.id?'编辑 Agent':'新建 Agent'}</h3><p>身份指令由你管理，并以 Codex 原生指令传入新会话。</p></div></div><label class="form-label">名称<input id="agentName" class="text-input" value="${attr(agent.name||'')}" placeholder="例如：代码审查员"></label><label class="form-label">身份指令<textarea id="agentInstructions" class="large-input" placeholder="描述角色、职责和工作约束">${esc(agent.instructions||'')}</textarea></label><div class="modal-actions"><button class="text-btn" data-action="closeAgent">取消</button><button class="primary-btn" data-action="saveAgent">保存</button></div></div></div>`;}
  function promptDialog(){if(!state.promptEditor)return'';const prompt=state.promptEditor;return `<div class="modal-overlay"><div class="modal-card prompt-dialog"><div class="modal-heading"><div><h3>${prompt.id?'编辑提示词':'新建提示词'}</h3><p>保存后可从聊天输入区快速启用，并在新会话中生效。</p></div></div><label class="form-label">名称<input id="promptName" class="text-input" value="${attr(prompt.name||'')}" placeholder="例如：程序"></label><label class="form-label">简短说明<input id="promptDescription" class="text-input" value="${attr(prompt.description||'')}" placeholder="说明这个提示词适合处理什么任务"></label><label class="form-label">提示词内容<textarea id="promptInstructions" class="large-input" placeholder="描述职责、工作方式和约束">${esc(prompt.instructions||'')}</textarea></label><div class="modal-actions"><button class="text-btn" data-action="closePrompt">取消</button><button class="primary-btn" data-action="savePrompt">保存</button></div></div></div>`;}
  function questionDialog(){if(!state.question)return'';const questions=state.question.questions||[],index=Math.max(0,Math.min(state.questionIndex,questions.length-1)),q=questions[index];if(!q)return'';const answer=state.questionAnswers[q.id]||{values:[],other:''},selected=answer.values[0]||'',options=Array.isArray(q.options)?q.options:[];return `<div class="modal-overlay question-overlay"><div class="modal-card question-dialog"><div class="modal-heading"><div><h3>Codex 有一些问题想问你</h3><p>不会自动关闭，你可以仔细比较每个方案。</p></div><span class="question-progress">${index+1} / ${questions.length}</span></div><div class="question-header"><span>${esc(q.header||'需要选择')}</span><p>${esc(q.question||'')}</p></div><div class="question-options">${options.map(option=>`<button class="question-option ${selected===option.label?'selected':''}" data-question-option="${attr(q.id)}" data-value="${attr(option.label)}"><span class="choice-mark">${selected===option.label?icon('check'):''}</span><span><b>${esc(option.label)}</b><small>${esc(option.description||'')}</small></span></button>`).join('')}${q.isOther?`<button class="question-option ${selected==='__other__'?'selected':''}" data-question-option="${attr(q.id)}" data-value="__other__"><span class="choice-mark">${selected==='__other__'?icon('check'):''}</span><span><b>其它</b><small>输入你自己的方案或补充细节</small></span></button>`:''}</div>${(!options.length||selected==='__other__')?`<textarea id="questionOther" class="large-input question-other${q.isSecret?' secret-input':''}" placeholder="请输入详细答案">${esc(answer.other||'')}</textarea>`:''}<div class="modal-actions"><button class="text-btn" data-action="cancelQuestions">取消</button>${index>0?'<button class="text-btn" data-action="questionBack">上一步</button>':''}<button class="primary-btn" data-action="questionNext">${index===questions.length-1?'提交':'下一步'}</button></div></div></div>`;}

  function mcpEditorDialog(){if(!state.mcpEditor)return'';const editor=state.mcpEditor;return `<div class="modal-overlay"><div class="modal-card mcp-editor-dialog"><div class="modal-heading"><div><h3>${editor.originalName?'编辑 MCP 服务器':'添加 MCP 服务器'}</h3><p>使用 Codex config.toml 支持的服务器字段。</p></div><button class="mcp-dialog-close" data-action="closeMcpEditor" title="关闭">${icon('close')}</button></div><label class="form-label">服务器名称<input id="mcpName" class="text-input" value="${attr(editor.name||'')}" placeholder="例如：github"></label><label class="form-label">JSON 配置<textarea id="mcpConfig" class="large-input mcp-json-input" spellcheck="false">${esc(editor.configText||'')}</textarea></label>${editor.error?`<div class="mcp-editor-error">${icon('alert')}<span>${esc(editor.error)}</span></div>`:''}<div class="mcp-config-hint">支持 STDIO 的 <code>command</code> / <code>args</code>，或远程服务器的 <code>url</code> 配置。</div><div class="modal-actions"><button class="text-btn" data-action="closeMcpEditor">取消</button><button class="primary-btn" data-action="saveMcp">保存</button></div></div></div>`;}
  function mcpDeleteDialog(){if(!state.mcpDeleteName)return'';return `<div class="modal-overlay"><div class="modal-card mcp-confirm-dialog"><div class="modal-heading"><div><h3>删除 MCP 服务器</h3><p>此操作会从 Codex config.toml 中移除服务器配置。</p></div></div><div class="mcp-confirm-content">${icon('alert')}<p>确定删除 <b>${esc(state.mcpDeleteName)}</b> 吗？</p></div><div class="modal-actions"><button class="text-btn" data-action="cancelDeleteMcp">取消</button><button class="primary-btn danger-btn" data-action="confirmDeleteMcp">删除</button></div></div></div>`;}
  function mcpHelpDialog(){if(!state.mcpHelp)return'';return `<div class="modal-overlay"><div class="modal-card mcp-help-dialog"><div class="modal-heading"><div><h3>什么是 MCP？</h3><p>Model Context Protocol 让 Codex 安全连接外部工具和数据源。</p></div><button class="mcp-dialog-close" data-action="closeMcpHelp" title="关闭">${icon('close')}</button></div><div class="mcp-help-content"><section><h4>${icon('server')}连接服务器</h4><p>可配置本地 STDIO 命令或远程 HTTP MCP 地址。保存后 Codex 会重新加载连接状态。</p></section><section><h4>${icon('code')}扩展工具</h4><p>服务器连接成功后，其公开的工具会显示在展开卡片中，并可在会话里由 Codex 调用。</p></section><section><h4>${icon('alert')}保护凭据</h4><p>复制配置会自动隐藏令牌、密码、Authorization 和 API Key 等敏感值。</p></section></div><div class="modal-actions"><button class="primary-btn" data-action="closeMcpHelp">知道了</button></div></div></div>`;}
  function mcpLogsDialog(){if(!state.mcpLogsOpen)return'';return `<div class="modal-overlay"><div class="modal-card mcp-logs-dialog"><div class="modal-heading"><div><h3>MCP 操作日志</h3><p>显示本次设置会话中的加载、连接、工具和配置操作。</p></div><div class="mcp-log-heading-actions">${state.mcpActivity.length?`<button class="mcp-dialog-close" data-action="clearMcpLogs" title="清空日志">${icon('trash')}</button>`:''}<button class="mcp-dialog-close" data-action="closeMcpLogs" title="关闭">${icon('close')}</button></div></div><div class="mcp-activity-list">${state.mcpActivity.length?state.mcpActivity.map(item=>`<div class="mcp-log-entry ${attr(item.level||'info')}"><time>${esc(item.time)}</time><i title="${attr(item.level||'info')}"></i><b>${item.serverName?`[${esc(item.serverName)}]`:''}</b><span>${esc(item.message)}</span></div>`).join(''):'<div class="mcp-activity-empty">暂无操作记录</div>'}</div><div class="modal-actions"><small>共 ${state.mcpActivity.length} 条日志</small><button class="primary-btn" data-action="closeMcpLogs">关闭</button></div></div></div>`;}
  function saveMcpEditor(){
    const name=document.getElementById('mcpName')?.value.trim()||'',configText=document.getElementById('mcpConfig')?.value||'';
    state.mcpEditor={...state.mcpEditor,name,configText,error:''};
    if(!/^[A-Za-z0-9_-]{1,64}$/.test(name)){state.mcpEditor.error='名称仅支持 1-64 位字母、数字、下划线和连字符。';render();return;}
    try{
      const config=JSON.parse(configText);
      if(!config||Array.isArray(config)||typeof config!=='object')throw new Error('配置必须是 JSON 对象');
      if(!(typeof config.command==='string'&&config.command.trim())&&!(typeof config.url==='string'&&config.url.trim()))throw new Error('配置必须包含 command 或 url');
      addMcpActivity(state.mcpEditor.originalName?'保存服务器配置':'添加服务器','info',name);
      post('saveMcp',{name,originalName:state.mcpEditor.originalName||'',config});
      state.mcpEditor=null;state.mcpAddOpen=false;render();
    }catch(error){state.mcpEditor.error=error.message||'JSON 配置无效';render();}
  }

  function render(preservePrompt=true){applyAppearance();const oldPrompt=preservePrompt?document.getElementById('prompt')?.value||'':'';const activeId=document.activeElement?.id,selectionStart=document.activeElement?.selectionStart,selectionEnd=document.activeElement?.selectionEnd;const oldMessages=document.getElementById('messages'),oldScrollTop=oldMessages?.scrollTop,oldSettingsScrollTop=document.querySelector('.settings-content')?.scrollTop;root.innerHTML=`<div class="app">${header()}${state.view==='chat'?chatPage():state.view==='history'?historyPage():settingsPage()}</div>${agentDialog()}${promptDialog()}${questionDialog()}${mcpEditorDialog()}${mcpDeleteDialog()}${mcpHelpDialog()}${mcpLogsDialog()}${state.toast?`<div class="toast">${esc(state.toast)}</div>`:''}`;const prompt=document.getElementById('prompt');if(prompt){prompt.value=oldPrompt;resizePrompt(prompt);}bind();const messages=document.getElementById('messages');if(messages&&oldScrollTop!==undefined)messages.scrollTop=oldScrollTop;const settingsContent=document.querySelector('.settings-content');if(settingsContent&&oldSettingsScrollTop!==undefined)settingsContent.scrollTop=oldSettingsScrollTop;const active=activeId&&document.getElementById(activeId);if(active){active.focus();if(typeof active.setSelectionRange==='function'&&selectionStart!==undefined)active.setSelectionRange(selectionStart,selectionEnd);}}
  function showToast(message,duration=2200){state.toast=message||'';clearTimeout(toastTimer);if(state.toast)toastTimer=setTimeout(()=>{if(state.toast===message){state.toast='';render();}},duration);}
  function resizePrompt(el){el.style.height='auto';el.style.height=Math.min(240,Math.max(84,el.scrollHeight))+'px';}
  function sendPrompt(){const prompt=document.getElementById('prompt'),text=prompt?.value.trim()||'';if(state.busy||(!text&&!state.attachments.length))return;post('send',{text});if(prompt)prompt.value='';}
  function storeQuestionText(){const q=state.question?.questions?.[state.questionIndex],input=document.getElementById('questionOther');if(q&&input){const current=state.questionAnswers[q.id]||{values:[],other:''};current.other=input.value;state.questionAnswers[q.id]=current;}}
  function questionReady(q){const answer=state.questionAnswers[q.id]||{values:[],other:''};if(!Array.isArray(q.options)||!q.options.length)return !!answer.other.trim();if(answer.values[0]==='__other__')return !!answer.other.trim();return !!answer.values[0];}
  function submitQuestions(){const answers={};for(const q of state.question.questions||[]){const value=state.questionAnswers[q.id]||{values:[],other:''};const selected=value.values[0]==='__other__'?value.other.trim():value.values[0]||(value.other||'').trim();answers[q.id]={answers:selected?[selected]:[]};}clearTimeout(questionTimer);post('answerQuestions',{requestId:state.question.requestId,answers});state.question=null;state.questionAnswers={};render();}
  function scheduleQuestionTimeout(){clearTimeout(questionTimer);if(!state.question)return;questionTimer=setTimeout(()=>{if(!state.question)return;post('cancelQuestions',{requestId:state.question.requestId});state.question=null;state.questionAnswers={};showToast('提问对话框已超时关闭');render();},Math.max(30,Math.min(3600,Number(state.permissionDialogTimeoutSeconds)||300))*1000);}

  function bind(){
    root.querySelectorAll('[data-action]').forEach(el=>el.onclick=e=>{e.stopPropagation();const action=el.dataset.action;
      if(action==='mcpHelp'){state.mcpHelp=true;render();return;}if(action==='closeMcpHelp'){state.mcpHelp=false;render();return;}if(action==='mcpLogs'){state.mcpLogsOpen=true;render();return;}if(action==='closeMcpLogs'){state.mcpLogsOpen=false;render();return;}if(action==='clearMcpLogs'){state.mcpActivity=[];addMcpActivity('日志已清空');render();return;}if(action==='mcpAddMenu'){state.mcpAddOpen=!state.mcpAddOpen;render();return;}if(action==='newMcp'){state.mcpEditor={originalName:'',name:'',configText:JSON.stringify({command:'npx',args:['-y','@modelcontextprotocol/server-example'],enabled:true},null,2),error:''};state.mcpAddOpen=false;render();return;}if(action==='closeMcpEditor'){state.mcpEditor=null;render();return;}if(action==='saveMcp'){saveMcpEditor();return;}if(action==='cancelDeleteMcp'){state.mcpDeleteName='';render();return;}if(action==='confirmDeleteMcp'){const name=state.mcpDeleteName;state.mcpDeleteName='';addMcpActivity(`删除服务器 ${name}`);post('deleteMcp',{name});render();return;}if(action==='reloadMcp'){state.mcpAddOpen=false;const serverName=el.dataset.mcpServer||'';addMcpActivity(serverName?'强制刷新工具列表':'正在刷新所有 MCP 服务器','info',serverName);addMcpActivity('正在加载 MCP 服务器列表');addMcpActivity('正在刷新服务器连接状态');post('reloadMcp');render();return;}if(action==='openMcpConfig'){state.mcpAddOpen=false;post('openMcpConfig');render();return;}
      if(action==='back'){state.view='chat';render();return;}if(action==='history'){state.view='history';post('history',{search:state.historySearch});render();return;}if(action==='settings'){state.view='settings';render();return;}if(action==='send'){sendPrompt();return;}if(action==='composerSettings'){state.composerMenu=!state.composerMenu;state.composerSubmenu=null;state.openMenu=null;render();return;}if(action==='toggleStatusPanel'){state.statusPanelExpanded=!state.statusPanelExpanded;if(!state.statusPanelExpanded)state.statusOpen=null;render();return;}if(action==='showFileContextPrompt'){state.fileContextPrompt=true;render();return;}if(action==='cancelFileContext'){state.fileContextPrompt=false;render();return;}if(action==='enableFileContext'){state.fileContextPrompt=false;state.sendOpenedFilePath=true;post('behaviorSetting',{key:'sendOpenedFilePath',value:true});render();return;}if(action==='clearFileContext'){state.sendOpenedFilePath=false;state.activeFile='';post('behaviorSetting',{key:'sendOpenedFilePath',value:false});render();return;}if(action==='toggleSkillImport'){state.skillImportOpen=!state.skillImportOpen;render();return;}if(action==='toggleReasoning'){post('toggleReasoning');return;}if(action==='toggleStreaming'){post('toggleStreaming');return;}
      if(action==='saveInstructions'){post('saveInstructions',{global:document.getElementById('globalInstructions')?.value||'',project:document.getElementById('projectInstructions')?.value||''});return;}if(action==='saveCustomSound'){const value=document.getElementById('customSoundPath')?.value.trim()||'';state.customSoundPath=value;post('behaviorSetting',{key:'customSoundPath',value});showToast('自定义提示音已保存');return;}if(action==='newAgent'){state.agentEditor={id:'',name:'',instructions:''};render();return;}if(action==='closeAgent'){state.agentEditor=null;render();return;}if(action==='saveAgent'){post('saveAgent',{id:state.agentEditor.id,name:document.getElementById('agentName')?.value||'',instructions:document.getElementById('agentInstructions')?.value||''});state.agentEditor=null;return;}if(action==='newPrompt'){state.promptEditor={id:'',name:'',description:'',instructions:''};render();return;}if(action==='closePrompt'){state.promptEditor=null;render();return;}if(action==='savePrompt'){post('savePrompt',{id:state.promptEditor.id,name:document.getElementById('promptName')?.value||'',description:document.getElementById('promptDescription')?.value||'',instructions:document.getElementById('promptInstructions')?.value||''});state.promptEditor=null;return;}
      if(action==='cancelQuestions'){clearTimeout(questionTimer);post('cancelQuestions',{requestId:state.question.requestId});state.question=null;render();return;}if(action==='questionBack'){storeQuestionText();state.questionIndex=Math.max(0,state.questionIndex-1);render();return;}if(action==='questionNext'){storeQuestionText();const q=state.question.questions[state.questionIndex];if(!questionReady(q)){showToast('请选择一个方案或填写详细答案');render();return;}if(state.questionIndex<state.question.questions.length-1){state.questionIndex++;render();}else submitQuestions();return;}if(action==='reconnect'){state.composerMenu=false;state.composerSubmenu=null;post('reconnect');render();return;}if((action==='acceptAll'||action==='revertAll')&&!state.changes.length){state.statusOpen=null;showToast('当前没有待处理的文件修改');render();return;}post(action);
    });
    root.querySelectorAll('[data-menu]').forEach(el=>el.onclick=e=>{e.stopPropagation();state.openMenu=state.openMenu===el.dataset.menu?null:el.dataset.menu;state.composerMenu=false;state.composerSubmenu=null;render();});root.querySelectorAll('[data-choice]').forEach(el=>el.onclick=e=>{e.stopPropagation();const key=el.dataset.choice,value=el.dataset.value;state[key]=value;state.openMenu=null;post('setting',{key,value});render();});root.querySelectorAll('[data-composer-submenu]').forEach(el=>el.onclick=e=>{e.stopPropagation();state.composerSubmenu=state.composerSubmenu===el.dataset.composerSubmenu?null:el.dataset.composerSubmenu;render();});
    root.querySelectorAll('[data-basic-tab]').forEach(el=>el.onclick=()=>{state.basicSettingsTab=el.dataset.basicTab;state.openMenu=null;render();});root.querySelectorAll('[data-appearance-theme]').forEach(el=>el.onclick=()=>updateAppearance('appearanceTheme',el.dataset.appearanceTheme,'theme'));root.querySelectorAll('[data-appearance-color]').forEach(el=>el.onclick=()=>updateAppearance(el.dataset.appearanceColor,el.dataset.value||'',el.dataset.storageKey));root.querySelectorAll('[data-color-picker]').forEach(el=>el.onchange=()=>updateAppearance(el.dataset.colorPicker,el.value,el.dataset.storageKey));root.querySelectorAll('[data-color-text]').forEach(el=>{const commit=()=>{const value=el.value.trim();if(/^#[0-9a-f]{6}$/i.test(value))updateAppearance(el.dataset.colorText,value,el.dataset.storageKey);else{el.value=state[el.dataset.colorText]||'';showToast('请输入 6 位十六进制颜色值');}};el.onblur=commit;el.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();commit();}};});const appearanceScale=document.getElementById('appearanceScale');if(appearanceScale)appearanceScale.onchange=()=>updateAppearance('appearanceScale',Number(appearanceScale.value),'scale');
    root.querySelectorAll('[data-send-shortcut]').forEach(el=>el.onclick=()=>{state.sendShortcut=el.dataset.sendShortcut;post('behaviorSetting',{key:'sendShortcut',value:state.sendShortcut});render();});root.querySelectorAll('[data-behavior-toggle]').forEach(el=>el.onclick=()=>{const key=el.dataset.behaviorToggle,value=!state[key];state[key]=value;post('behaviorSetting',{key,value});render();});const timeoutInput=document.getElementById('permissionDialogTimeout');if(timeoutInput){const commit=()=>{const value=Math.max(30,Math.min(3600,Math.trunc(Number(timeoutInput.value)||300)));state.permissionDialogTimeoutSeconds=value;post('behaviorSetting',{key:'permissionDialogTimeoutSeconds',value});timeoutInput.value=String(value);};timeoutInput.onblur=commit;timeoutInput.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();commit();}};}root.querySelectorAll('[data-sound-menu]').forEach(el=>el.onclick=e=>{e.stopPropagation();state.soundMenuOpen=!state.soundMenuOpen;render();});root.querySelectorAll('[data-sound-option]').forEach(el=>el.onclick=e=>{e.stopPropagation();state.notificationSound=el.dataset.soundOption;state.soundMenuOpen=false;post('behaviorSetting',{key:'notificationSound',value:state.notificationSound});render();});const customSoundPath=document.getElementById('customSoundPath');if(customSoundPath)customSoundPath.onblur=()=>{const value=customSoundPath.value.trim();state.customSoundPath=value;post('behaviorSetting',{key:'customSoundPath',value});};
    root.querySelectorAll('[data-settings-tab]').forEach(el=>el.onclick=()=>{state.settingsTab=el.dataset.settingsTab;if(state.settingsTab==='mcp'){addMcpActivity(state.mcpActivity.length?'正在加载 MCP 服务器列表':'首次加载 MCP 服务器数据');addMcpActivity('正在刷新服务器连接状态');post('loadMcp');}if(state.settingsTab==='skills')post('loadSkills');render();});root.querySelectorAll('[data-settings-go]').forEach(el=>el.onclick=()=>{state.view='settings';state.settingsTab=el.dataset.settingsGo;state.composerMenu=false;state.composerSubmenu=null;if(state.settingsTab==='mcp'){addMcpActivity(state.mcpActivity.length?'正在加载 MCP 服务器列表':'首次加载 MCP 服务器数据');addMcpActivity('正在刷新服务器连接状态');post('loadMcp');}if(state.settingsTab==='skills')post('loadSkills');render();});root.querySelectorAll('[data-status]').forEach(el=>el.onclick=()=>{state.statusOpen=state.statusOpen===el.dataset.status?null:el.dataset.status;render();});
    root.querySelectorAll('[data-thread]').forEach(el=>el.onclick=()=>post('openThread',{id:el.dataset.thread}));root.querySelectorAll('[data-anchor]').forEach(el=>el.onclick=()=>document.querySelector(`[data-message="${el.dataset.anchor}"]`)?.scrollIntoView({behavior:'smooth',block:'start'}));root.querySelectorAll('[data-open-change]').forEach(el=>el.onclick=()=>post('openChange',{index:Number(el.dataset.openChange)}));root.querySelectorAll('[data-accept]').forEach(el=>el.onclick=()=>post('acceptChange',{index:Number(el.dataset.accept)}));root.querySelectorAll('[data-revert]').forEach(el=>el.onclick=()=>post('revertChange',{index:Number(el.dataset.revert)}));root.querySelectorAll('[data-remove-attachment]').forEach(el=>el.onclick=()=>post('removeAttachment',{index:Number(el.dataset.removeAttachment)}));
    root.querySelectorAll('[data-agent-select]').forEach(el=>el.onclick=()=>post('selectAgent',{id:el.dataset.agentSelect||''}));root.querySelectorAll('[data-agent-edit]').forEach(el=>el.onclick=()=>{const agent=state.agents.find(item=>item.id===el.dataset.agentEdit);if(agent){state.agentEditor={...agent};render();}});root.querySelectorAll('[data-agent-delete]').forEach(el=>el.onclick=()=>post('deleteAgent',{id:el.dataset.agentDelete}));root.querySelectorAll('[data-prompt-select]').forEach(el=>el.onclick=()=>post('selectPrompt',{id:el.dataset.promptSelect||''}));root.querySelectorAll('[data-prompt-edit]').forEach(el=>el.onclick=()=>{const prompt=state.prompts.find(item=>item.id===el.dataset.promptEdit);if(prompt){state.promptEditor={...prompt};render();}});root.querySelectorAll('[data-prompt-delete]').forEach(el=>el.onclick=()=>post('deletePrompt',{id:el.dataset.promptDelete}));root.querySelectorAll('[data-question-option]').forEach(el=>el.onclick=()=>{storeQuestionText();state.questionAnswers[el.dataset.questionOption]={values:[el.dataset.value],other:state.questionAnswers[el.dataset.questionOption]?.other||''};render();});
    root.querySelectorAll('[data-skill-select]').forEach(el=>el.onclick=()=>{state.selectedSkillPath=state.selectedSkillPath===el.dataset.skillSelect?'':el.dataset.skillSelect;render();});root.querySelectorAll('[data-skill-scope]').forEach(el=>el.onclick=()=>{state.skillScope=el.dataset.skillScope;render();});root.querySelectorAll('[data-skill-status]').forEach(el=>el.onclick=()=>{state.skillStatus=el.dataset.skillStatus;render();});root.querySelectorAll('[data-open-skill]').forEach(el=>el.onclick=()=>post('openSkill',{path:el.dataset.openSkill||''}));root.querySelectorAll('[data-mcp-expand]').forEach(el=>el.onclick=()=>{state.expandedMcpName=state.expandedMcpName===el.dataset.mcpExpand?'':el.dataset.mcpExpand;render();});root.querySelectorAll('[data-mcp-edit]').forEach(el=>el.onclick=e=>{e.stopPropagation();const server=state.mcpServers.find(item=>item.name===el.dataset.mcpEdit);if(server&&!server.managed){state.mcpEditor={originalName:server.name,name:server.name,configText:JSON.stringify(server.config||{},null,2),error:''};render();}});root.querySelectorAll('[data-mcp-copy]').forEach(el=>el.onclick=e=>{e.stopPropagation();const server=state.mcpServers.find(item=>item.name===el.dataset.mcpCopy);if(server){post('copyText',{text:mcpCopyText(server)});addMcpActivity(`复制服务器 ${server.name} 的配置`);showToast('MCP 配置已复制，敏感值已隐藏');render();}});root.querySelectorAll('[data-mcp-delete]').forEach(el=>el.onclick=e=>{e.stopPropagation();const server=state.mcpServers.find(item=>item.name===el.dataset.mcpDelete);if(server&&!server.managed){state.mcpDeleteName=server.name;render();}});root.querySelectorAll('[data-mcp-toggle]').forEach(el=>el.onclick=e=>{e.stopPropagation();const server=state.mcpServers.find(item=>item.name===el.dataset.mcpToggle);if(server&&!server.managed){server.enabled=server.enabled===false;addMcpActivity(`${server.enabled?'启用':'停用'}服务器 ${server.name}`);post('setMcpEnabled',{name:server.name,enabled:server.enabled});render();}});root.querySelectorAll('[data-mcp-login]').forEach(el=>el.onclick=e=>{e.stopPropagation();addMcpActivity(`登录服务器 ${el.dataset.mcpLogin}`);post('loginMcp',{name:el.dataset.mcpLogin||''});render();});
    root.querySelectorAll('[data-copy]').forEach(el=>el.onclick=()=>navigator.clipboard.writeText(el.dataset.copy||''));root.querySelectorAll('a').forEach(el=>el.onclick=e=>{e.preventDefault();post('openUrl',{url:el.href});});root.querySelectorAll('[data-skill-import]').forEach(el=>el.onclick=e=>{e.stopPropagation();state.skillImportOpen=false;post('importSkill',{scope:el.dataset.skillImport});render();});root.querySelectorAll('[data-skill-toggle]').forEach(el=>el.onclick=e=>{e.stopPropagation();const skill=state.skills.find(item=>item.path===el.dataset.skillToggle),enabled=skill?skill.enabled!==false:el.classList.contains('checked');if(skill)skill.enabled=!enabled;post('setSkillEnabled',{path:el.dataset.skillToggle||'',enabled:!enabled});render();});const prompt=document.getElementById('prompt');if(prompt){prompt.oninput=()=>resizePrompt(prompt);prompt.onkeydown=e=>{const sendWithModifier=state.sendShortcut==='cmdEnter'&&(e.ctrlKey||e.metaKey),sendWithEnter=state.sendShortcut!=='cmdEnter'&&!e.shiftKey;if(e.key==='Enter'&&!e.isComposing&&(sendWithModifier||sendWithEnter)){e.preventDefault();sendPrompt();}};}const history=document.getElementById('historySearch');if(history){let timer;history.oninput=()=>{state.historySearch=history.value;clearTimeout(timer);timer=setTimeout(()=>post('history',{search:history.value}),180);};}const skillSearch=document.getElementById('skillSearch');if(skillSearch)skillSearch.oninput=()=>{state.skillSearch=skillSearch.value;render();};root.onclick=()=>{if(state.openMenu||state.composerMenu||state.mcpAddOpen||state.skillImportOpen||state.soundMenuOpen||state.fileContextPrompt){state.openMenu=null;state.composerMenu=false;state.composerSubmenu=null;state.mcpAddOpen=false;state.skillImportOpen=false;state.soundMenuOpen=false;state.fileContextPrompt=false;render();}};
  }
  function followsLatestMessage(){const el=document.getElementById('messages');return !el||el.scrollHeight-el.clientHeight-el.scrollTop<48;}
  function scrollBottom(){const el=document.getElementById('messages');if(el)el.scrollTop=el.scrollHeight;}
  window.CodexGui={receive(event){const e=typeof event==='string'?JSON.parse(event):event,followLatest=followsLatestMessage();switch(e.type){case'bootstrap':Object.assign(state,e.state||{});break;case'connection':state.connected=!!e.connected;if(!e.connected&&e.detail)showToast(e.detail);break;case'busy':state.busy=!!e.busy;break;case'clear':state.messages=[];state.title=e.title||'新会话';state.threadId=e.threadId||null;state.usagePercentage=0;state.usageUsedTokens=0;state.usageMaxTokens=0;break;case'message':state.messages.push(e.entry);break;case'replaceMessage':{const i=state.messages.findIndex(m=>m.itemId===e.entry.itemId);if(i>=0)state.messages[i]=e.entry;else state.messages.push(e.entry);break;}case'history':state.history=e.items||[];break;case'changes':state.changes=e.items||[];if(state.diffExpandedByDefault&&state.changes.length){state.statusPanelExpanded=true;state.statusOpen='changes';}break;case'attachments':state.attachments=e.items||[];break;case'fileContext':state.activeFile=e.path||'';break;case'usage':state.usagePercentage=Number(e.percentage)||0;state.usageUsedTokens=Number(e.usedTokens)||0;state.usageMaxTokens=Number(e.maxTokens)||0;break;case'thread':state.threadId=e.id||null;state.title=e.title||state.title;state.view='chat';break;case'mcpServers':state.mcpServers=e.items||[];addMcpActivity(`成功加载 ${state.mcpServers.length} 个 MCP 服务器`,'success');logMcpSnapshot(state.mcpServers);if(!state.mcpServers.some(item=>item.name===state.expandedMcpName))state.expandedMcpName=state.mcpServers[0]?.name||'';break;case'mcpLog':addMcpActivity(e.message||'',e.level||'info',e.serverName||'');break;case'skillEnabled':{const skill=state.skills.find(item=>item.path===e.path);if(skill)skill.enabled=!!e.enabled;break;}case'skills':state.skills=e.items||[];state.skillErrors=e.errors||[];break;case'question':state.question={requestId:e.requestId,questions:e.questions||[]};state.questionIndex=0;state.questionAnswers={};scheduleQuestionTimeout();break;case'toast':showToast(e.message||'');break;}render();if(followLatest&&['message','replaceMessage','clear'].includes(e.type))scrollBottom();}};
  try{matchMedia('(prefers-color-scheme: light)').addEventListener('change',()=>{if(state.appearanceTheme==='system')render();});}catch(_){}
  render(false);post('ready');
})();
